#!/usr/bin/env python3
# build_schedule.py - turn an executed bring-up stream into a SCHEDULE plus a
# residual, so the generators can run LIVE in the right order.
#
# WHY THIS EXISTS
#
# alpha64 showed the dataplane comes up with no vendor replay by replaying
# /mnt/flash/bringup.txt -- the deterministic output of the generator
# transformation. That works, but it is a frozen artifact: no generator runs, the
# boot log correctly reports "0 of 90396 executed writes come from our
# generators", and the file carries the vendor's values inline so it cannot be
# redistributed.
#
# The fix is to keep the ORDER and throw away the frozen values. Each generator's
# output appears in the stream as one contiguous block, so the stream decomposes
# into an alternating sequence:
#
#     RES <n>        apply the next n writes from the residual
#     GEN <tool>     run this generator, live, from our own source
#
# A schedule is an ordering of our own writes. It contains no vendor values; the
# only vendor data left is the residual, which is what no generator covers yet.
#
# ⚠ A generator is placed ONLY if its entire -n output matches the stream exactly
# and contiguously. Anything that does not match is left in the residual rather
# than guessed at -- a mis-placed block would reorder the bring-up, and ordering
# is the one thing this whole exercise established you cannot get wrong.
#
# ⚠ Generators applied by direct MMIO (ffuinit, l2linit, hashinit, ffubstinit)
# are legitimately absent: gen_drop removed their lines from the stream and the
# sequence runs them separately, before the replay. Do not try to place them.
#
# SPDX-License-Identifier: GPL-2.0-or-later
import os, glob, argparse

def rows(path):
    o = []
    for line in open(path):
        f = line.split()
        if len(f) == 2:
            try: o.append((int(f[0], 16), int(f[1], 16)))
            except ValueError: pass
    return o

def find_block(stream, block, taken):
    """First index where block occurs contiguously and does not overlap a
    already-placed span. Returns -1 if absent."""
    n, first = len(block), block[0]
    for i in range(len(stream) - n + 1):
        if stream[i] != first: continue
        if any(taken[i:i + n]): continue
        if stream[i:i + n] == block: return i
    return -1

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("stream", help="executed bring-up stream (fwd-executed.txt)")
    ap.add_argument("--gens", required=True, help="dir of <tool>.n ordered write dumps")
    ap.add_argument("--out-schedule", default="schedule.txt")
    ap.add_argument("--out-residual", default="resid.txt")
    a = ap.parse_args()

    ex = rows(a.stream)
    taken = [False] * len(ex)
    placed = []
    for p in sorted(glob.glob(os.path.join(a.gens, "*.n"))):
        # A dump may be named "<tool>@<arg>@<arg>.n" for a generator that emits
        # only part of its output. fm6000_sbusseq needs this: its writes form 12
        # interleaved runs in the stream, so no single point is the right place
        # for all of them and it is scheduled one segment at a time.
        name = os.path.basename(p)[:-2].replace("@", " ")
        g = rows(p)
        if not g: continue
        i = find_block(ex, g, taken)
        if i < 0: continue
        for k in range(i, i + len(g)): taken[k] = True
        placed.append((i, len(g), name))
    placed.sort()

    steps, resid, run = [], [], 0
    pos = 0
    for start, length, name in placed:
        gap = ex[pos:start]
        for w in gap: resid.append(w)
        if gap: steps.append("RES %d" % len(gap))
        steps.append("GEN %s" % name)
        pos = start + length
    tail = ex[pos:]
    for w in tail: resid.append(w)
    if tail: steps.append("RES %d" % len(tail))

    with open(a.out_schedule, "w") as f:
        f.write("# generated by build_schedule.py -- ordering only, no vendor values\n")
        f.write("# steps: RES <n> = next n writes from the residual; GEN <tool> = run it live\n")
        for s in steps: f.write(s + "\n")
    with open(a.out_residual, "w") as f:
        for addr, val in resid: f.write("%08x %08x\n" % (addr, val))

    gen_writes = sum(l for _, l, _ in placed)
    print("stream            : %d writes" % len(ex))
    print("generator blocks  : %d, covering %d writes (%.1f%%)"
          % (len(placed), gen_writes, 100.0 * gen_writes / len(ex)))
    print("residual          : %d writes (%.1f%%) -- the only vendor data left"
          % (len(resid), 100.0 * len(resid) / len(ex)))
    print("schedule          : %d steps" % len(steps))
    print("\nwrote %s and %s" % (a.out_schedule, a.out_residual))

if __name__ == "__main__":
    main()
