#!/usr/bin/env python3
# build_schedule.py - turn an executed bring-up stream into a SCHEDULE plus a
# residual, so the generators can run LIVE in the right order.
#
# WHY THIS EXISTS
#
# alpha64 showed the dataplane comes up with no vendor replay by replaying
# /mnt/flash/bringup.txt -- the deterministic output of the generator
# transformation. That works, but it is a frozen artifact: no generator runs, the
# boot log correctly reports "0 of 90396 executed writes come from our
# generators", and the file carries the vendor's values inline so it cannot be
# redistributed.
#
# The fix is to keep the ORDER and throw away the frozen values. Each generator's
# output appears in the stream as one contiguous block, so the stream decomposes
# into an alternating sequence:
#
#     RES <n>        apply the next n writes from the residual
#     GEN <tool>     run this generator, live, from our own source
#
# A schedule is an ordering of our own writes. It contains no vendor values; the
# only vendor data left is the residual, which is what no generator covers yet.
#
# ⚠ A generator is placed ONLY if its entire -n output matches the stream exactly
# and contiguously. Anything that does not match is left in the residual rather
# than guessed at -- a mis-placed block would reorder the bring-up, and ordering
# is the one thing this whole exercise established you cannot get wrong.
#
# ⚠ Generators applied by direct MMIO (ffuinit, l2linit, hashinit, ffubstinit)
# are legitimately absent: gen_drop removed their lines from the stream and the
# sequence runs them separately, before the replay. Do not try to place them.
#
# SPDX-License-Identifier: GPL-2.0-or-later
import os, glob, argparse

def rows(path):
    o = []
    for line in open(path):
        f = line.split()
        if len(f) == 2:
            try: o.append((int(f[0], 16), int(f[1], 16)))
            except ValueError: pass
    return o

def find_block(stream, block, taken):
    """First index where block occurs contiguously and does not overlap a
    already-placed span. Returns -1 if absent."""
    n, first = len(block), block[0]
    for i in range(len(stream) - n + 1):
        if stream[i] != first: continue
        if any(taken[i:i + n]): continue
        if stream[i:i + n] == block: return i
    return -1

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("stream", help="executed bring-up stream (fwd-executed.txt)")
    ap.add_argument("--gens", required=True, help="dir of <tool>.n ordered write dumps")
    ap.add_argument("--out-schedule", default="schedule.txt")
    ap.add_argument("--out-residual", default="resid.txt")
    a = ap.parse_args()

    ex = rows(a.stream)
    taken = [False] * len(ex)

    # ⚠ PLACE LONGEST BLOCKS FIRST. Placing in name order let a short, highly
    # repetitive segment land INSIDE a longer block's span and block it:
    # fm6000_sbusseq segment 7 is 54 writes occurring 12 times in the stream,
    # and one of those occurrences sits inside segment 8, which is 540 writes
    # occurring exactly ONCE. Greedy name-order placement took the short one
    # first, and segment 8 could then never be placed.
    #
    # That is not a cosmetic loss. A PARTIALLY placed generator is worse than an
    # unplaced one: the segments left behind stay in the residual and run at a
    # different point relative to the generated ones, which reorders the
    # bring-up. Scheduling SBus with 11 of its 12 segments took Et2 DOWN in
    # silicon while the box still forwarded over Et1 -- alpha66.
    #
    # Longest-first fixes it: a long block claims its span before any short
    # block can squat inside it.
    #
    # A dump may be named "<tool>@<arg>@<arg>.n" for a generator that emits only
    # part of its output, which is how the 12 interleaved SBus runs are placed.
    cands = []
    for path in sorted(glob.glob(os.path.join(a.gens, "*.n"))):
        g = rows(path)
        if g: cands.append((os.path.basename(path)[:-2].replace("@", " "), g))
    cands.sort(key=lambda c: -len(c[1]))

    placed, unplaced = [], []
    for name, g in cands:
        i = find_block(ex, g, taken)
        if i < 0:
            unplaced.append((name, len(g)))
            continue
        for k in range(i, i + len(g)): taken[k] = True
        placed.append((i, len(g), name))
    placed.sort()
    steps, resid, run = [], [], 0
    pos = 0
    for start, length, name in placed:
        gap = ex[pos:start]
        for w in gap: resid.append(w)
        if gap: steps.append("RES %d" % len(gap))
        steps.append("GEN %s" % name)
        pos = start + length
    tail = ex[pos:]
    for w in tail: resid.append(w)
    if tail: steps.append("RES %d" % len(tail))

    with open(a.out_schedule, "w") as f:
        f.write("# generated by build_schedule.py -- ordering only, no vendor values\n")
        f.write("# steps: RES <n> = next n writes from the residual; GEN <tool> = run it live\n")
        for s in steps: f.write(s + "\n")
    with open(a.out_residual, "w") as f:
        for addr, val in resid: f.write("%08x %08x\n" % (addr, val))

    gen_writes = sum(l for _, l, _ in placed)
    print("stream            : %d writes" % len(ex))
    print("generator blocks  : %d, covering %d writes (%.1f%%)"
          % (len(placed), gen_writes, 100.0 * gen_writes / len(ex)))
    print("residual          : %d writes (%.1f%%) -- the only vendor data left"
          % (len(resid), 100.0 * len(resid) / len(ex)))
    print("schedule          : %d steps" % len(steps))
    if unplaced:
        # Never silent. An unplaced generator means its writes are still vendor
        # data in the residual; a PARTIALLY placed one is a live hazard.
        print("\nunplaced (%d) -- these writes remain vendor data:" % len(unplaced))
        for name, n in sorted(unplaced, key=lambda u: -u[1])[:10]:
            print("   %-34s %d writes" % (name, n))
        fam_placed = {p[2].split()[0] for p in placed}
        partial = sorted({n.split()[0] for n, _ in unplaced} & fam_placed)
        if partial:
            print("\n⚠ PARTIALLY PLACED, DO NOT SHIP THIS SCHEDULE: %s" % ", ".join(partial))
    print("\nwrote %s and %s" % (a.out_schedule, a.out_residual))

if __name__ == "__main__":
    main()
