#!/usr/bin/env python3
# checklist.py - regenerate the measured STATUS block of
# docs/FEATURE-COMPLETE-CHECKLIST.md.
#
# That document is the single source of truth for "what is still needed to run
# this switch on our own code". Its prose is hand-written; its NUMBERS are not,
# because hand-maintained numbers drift and this project has already published
# three different figures for the same quantity.
#
#   checklist.py                 print the status block
#   checklist.py --update        rewrite it in place, between the markers
#
# Measurements come from the same tools that produce them elsewhere, so the
# checklist cannot disagree with provenance_audit.py or ucode_overlap.py:
#
#   provenance_audit.py   AUTHORED / TABLE / RELOCATED pair counts
#   ucode_overlap.py      vendor microcode pairs embedded in our C
#   the residual          writes the operator must still supply
#
# SPDX-License-Identifier: GPL-2.0-or-later
import subprocess, re, sys, os, argparse

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
DOC = os.path.join(ROOT, "docs", "FEATURE-COMPLETE-CHECKLIST.md")
BEGIN = "<!-- STATUS:BEGIN -- generated by asic/fm6000/tools/checklist.py, do not edit by hand -->"
END = "<!-- STATUS:END -->"

def run(*a):
    try:
        return subprocess.run([sys.executable] + list(a), capture_output=True,
                              text=True, cwd=ROOT, timeout=900).stdout
    except Exception as e:
        return "ERROR %s" % e

def status(residual=None, ucode=None):
    prov = run(os.path.join(HERE, "provenance_audit.py"))
    g = {}
    for k in ("AUTHORED", "TABLE", "RELOCATED"):
        m = re.search(r"^%s\s+([\d,]+) pairs in (\d+) files" % k, prov, re.M)
        if m: g[k] = (int(m.group(1).replace(",", "")), int(m.group(2)))

    uc_total = uc_files = None
    top = []
    if ucode:
        out = run(os.path.join(HERE, "ucode_overlap.py"), *ucode)
        m = re.search(r"embedded in our C: (\d+) of (\d+) \(([\d.]+)%\), across (\d+) files", out)
        if m: uc_total, uc_all, uc_pct, uc_files = (int(m.group(1)), int(m.group(2)),
                                                    m.group(3), int(m.group(4)))
        for line in out.splitlines():
            mm = re.match(r"^(fm6000_\S+\.c)\s+\d+\s+(\d+)\s+\d+%", line)
            if mm and len(top) < 5: top.append((mm.group(1), int(mm.group(2))))

    res_w = res_a = None
    if residual and os.path.exists(residual):
        seen = set(); n = 0
        for line in open(residual):
            f = line.split()
            if len(f) == 2:
                n += 1; seen.add(f[0])
        res_w, res_a = n, len(seen)

    L = [BEGIN, ""]
    L.append("### Measured status")
    L.append("")
    L.append("| | count | |")
    L.append("|---|---:|---|")
    if uc_total is not None:
        L.append("| **vendor microcode verbatim in our C** | **%d** | of %d non-trivial pairs "
                 "(%s%%), across %d files — *this is the redistribution blocker* |"
                 % (uc_total, uc_all, uc_pct, uc_files))
    for k, label in (("RELOCATED", "transcribed vendor writes in our C"),
                     ("TABLE", "table-grade (our placement, vendor values)"),
                     ("AUTHORED", "authored from intent")):
        if k in g:
            L.append("| %s | %s | in %d files |" % (label, "{:,}".format(g[k][0]), g[k][1]))
    if res_w is not None:
        L.append("| vendor writes the operator must supply | %s | over %s addresses |"
                 % ("{:,}".format(res_w), "{:,}".format(res_a)))
    L.append("")
    if top:
        L.append("Files carrying the most vendor microcode:")
        L.append("")
        L.append("    " + "\n    ".join("%-24s %5d" % t for t in top))
        L.append("")
    L.append("⚠ **AUTHORED does not mean zero vendor bytes.** The grade describes how the")
    L.append("*structure* was recovered; several authored files still carry vendor *values*.")
    L.append("Both the microcode row and the RELOCATED row must reach zero.")
    L.append("")
    L.append(END)
    return "\n".join(L)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--residual", help="resid.txt as shipped")
    ap.add_argument("--ucode", nargs="*", help="operator microcode files")
    ap.add_argument("--update", action="store_true", help="rewrite the block in the doc")
    a = ap.parse_args()
    block = status(a.residual, a.ucode)
    if not a.update:
        print(block); return
    s = open(DOC).read()
    if BEGIN in s and END in s:
        s = s[:s.index(BEGIN)] + block + s[s.index(END) + len(END):]
    else:
        lines = s.split("\n")
        for i, l in enumerate(lines):
            if l.startswith("## "):
                s = "\n".join(lines[:i] + [block, ""] + lines[i:]); break
    open(DOC, "w").write(s)
    print("updated %s" % DOC)

if __name__ == "__main__":
    main()
