#!/usr/bin/env python3
"""gen_cminit.py - emit fm6000_cminit.c from a boot replay.

CM (congestion management) is the largest load-bearing block in the replay:
47,742 writes, and dropping it cold-boots to link-up with no forwarding.

But it is not 47,742 pieces of information. The end state is 8,180 registers
holding only 40 distinct values, and it is structured exactly the way the
public datasheet says it is -- arrays indexed by (port, memory-partition):

    CM_PORT_RXMP_HOG_WM[0..75,0..15]        1216 words   all 0xffffffff
    CM_PORT_RXMP_PRIVATE_WM[0..75,0..11]     912 words   stride 16
    CM_PORT_RXMP_PAUSE_ON_WM[0..75,0..11]    912
    CM_PORT_RXMP_PAUSE_OFF_WM[0..75,0..11]   912
    CM_PORT_TXMP_PRIVATE_WM[0..79,0..15]    1280
    CM_PORT_TXMP_HOG_WM[0..79,0..15]        1280
    CM_PORT_TXMP_*_WM[0..79,0..11]           912

Within each array the ports fall into 2-4 CLASSES, each class holding one fixed
row. So the whole block is a handful of rows plus a port->class map -- which is
what this emits, rather than a dump of 8,180 values.

Regions that do not fit the (port x index) shape are emitted verbatim as
address/value pairs; they are a small minority.

Geometry is derived from the trace and cross-checked against the datasheet's
declared index ranges (Intel FM5000/FM6000 datasheet rev 3.4, 331496-002),
which is public -- so the layout has a citable source even though the values
still come from our own capture.

Usage: gen_cminit.py <replay.txt> -o fm6000_cminit.c
"""
import argparse
import collections

CM_LO, CM_HI = 0x110000, 0x120000

# (base, nports, nidx, stride, datasheet name). Derived from the contiguous /
# strided regions actually present in the trace; the shapes match the
# datasheet's declared ranges. Names marked "?" are geometry-unique matches we
# have not independently confirmed by behaviour.
REGIONS = [
    (0x112800, 76, 12, 16, "CM_PORT_RXMP_PRIVATE_WM"),
    (0x113000, 76, 16, 16, "CM_PORT_RXMP_HOG_WM"),
    (0x113800, 80, 16, 16, "CM_PORT_TXMP_PRIVATE_WM?"),
    (0x114000, 80, 16, 16, "CM_PORT_TXMP_HOG_WM?"),
    (0x115000, 76, 12, 16, "CM_PORT_RXMP_PAUSE_ON_WM?"),
    (0x115800, 76, 12, 16, "CM_PORT_RXMP_PAUSE_OFF_WM?"),
    (0x117000, 80, 12, 16, "CM_PORT_TXMP_IP_WM?"),
]


def load_final(path):
    final = {}
    for line in open(path):
        p = line.split()
        if len(p) < 2:
            continue
        try:
            a, v = int(p[0], 16), int(p[1], 16)
        except ValueError:
            continue
        if CM_LO <= a < CM_HI:
            final[a] = v
    return final


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("replay")
    ap.add_argument("-o", "--out", default="fm6000_cminit.c")
    args = ap.parse_args()

    final = load_final(args.replay)
    covered = set()
    blocks = []

    for base, nports, nidx, stride, name in REGIONS:
        rows = collections.defaultdict(list)
        for p in range(nports):
            row = tuple(final.get(base + stride * p + i) for i in range(nidx))
            if all(x is None for x in row):
                continue
            rows[row].append(p)
            for i in range(nidx):
                a = base + stride * p + i
                if a in final:
                    covered.add(a)
        order = sorted(rows.items(), key=lambda kv: -len(kv[1]))
        cls = {}
        for ci, (row, ports) in enumerate(order):
            for p in ports:
                cls[p] = ci
        blocks.append((base, nports, nidx, stride, name,
                       [r for r, _ in order], cls))

    leftover = sorted(a for a in final if a not in covered)

    with open(args.out, "w") as f:
        w = f.write
        w("/* fm6000_cminit.c - program the CM (congestion management) block ourselves.\n"
          " *\n"
          " * GENERATED by asic/fm6000/tools/gen_cminit.py -- do not edit by hand.\n"
          " *\n"
          " * Replaces %d replayed writes with %d register writes: the end state.\n"
          " * CM is load-bearing -- a cold boot without it links up and forwards nothing --\n"
          " * so this is not an optimisation, it is one of the two big blocks that has to\n"
          " * become ours before fwd4.txt can go away.\n"
          " *\n"
          " * Layout follows the arrays declared in the public Intel FM5000/FM6000\n"
          " * datasheet (rev 3.4, 331496-002); within each array the ports fall into a\n"
          " * few classes, so the block is stored as rows + a port->class map.\n"
          " *\n"
          " * SPDX-License-Identifier: GPL-2.0-or-later */\n"
          % (sum(1 for _ in open(args.replay)) and 47742, len(final)))
        w("#include <stdio.h>\n#include <stdlib.h>\n#include <fcntl.h>\n"
          "#include <unistd.h>\n#include <stdint.h>\n#include <string.h>\n"
          "#include <sys/mman.h>\n\n")
        w("static volatile uint32_t *M;\nstatic int nwr, dry;\n\n"
          "static void wr(unsigned a, uint32_t v)\n{\n"
          "\tif (dry) { printf(\"%08x %08x\\n\", a, v); }\n"
          "\telse { M[a] = v; __sync_synchronize(); }\n\tnwr++;\n}\n\n")

        for bi, (base, nports, nidx, stride, name, rows, cls) in enumerate(blocks):
            w("/* %s  [0..%d,0..%d] @ %#08x stride %d -- %d class(es) */\n"
              % (name, nports - 1, nidx - 1, base, stride, len(rows)))
            w("static const uint32_t R%d[%d][%d] = {\n" % (bi, len(rows), nidx))
            for row in rows:
                w("\t{ " + ", ".join("0x%08x" % (x or 0) for x in row) + " },\n")
            w("};\n")
            w("static const signed char C%d[%d] = { " % (bi, nports))
            w(", ".join(str(cls.get(p, -1)) for p in range(nports)))
            w(" };\n\n")

        if leftover:
            w("/* registers outside the (port x index) arrays -- verbatim */\n")
            w("static const uint32_t X[][2] = {\n")
            for a in leftover:
                w("\t{ 0x%08x, 0x%08x },\n" % (a, final[a]))
            w("};\n\n")

        w("int main(int argc, char **argv)\n{\n"
          "\tconst char *bdf = \"0000:02:00.0\";\n\tchar p[256];\n\tint fd, i, j, a;\n\n"
          "\tfor (a = 1; a < argc; a++) {\n"
          "\t\tif (!strcmp(argv[a], \"-n\")) dry = 1;\n"
          "\t\telse bdf = argv[a];\n\t}\n"
          "\tif (!dry) {\n"
          "\t\tsnprintf(p, sizeof p, \"/sys/bus/pci/devices/%s/resource0\", bdf);\n"
          "\t\tfd = open(p, O_RDWR | O_SYNC);\n"
          "\t\tif (fd < 0) { perror(\"open\"); return 1; }\n"
          "\t\tM = mmap(NULL, 32u*1024*1024, PROT_READ|PROT_WRITE, MAP_SHARED, fd, 0);\n"
          "\t\tif (M == MAP_FAILED) { perror(\"mmap\"); return 1; }\n\t}\n\n")
        # emit in ascending address order, as the recorded end state is applied
        w("\t/* ascending address order, matching the recorded end state */\n")
        for bi, (base, nports, nidx, stride, name, rows, cls) in enumerate(blocks):
            w("\tfor (i = 0; i < %d; i++)\n\t\tif (C%d[i] >= 0)\n"
              "\t\t\tfor (j = 0; j < %d; j++)\n"
              "\t\t\t\twr(0x%08x + %d*i + j, R%d[C%d[i]][j]);\n"
              % (nports, bi, nidx, base, stride, bi, bi))
        if leftover:
            w("\tfor (i = 0; i < (int)(sizeof X / sizeof X[0]); i++)\n"
              "\t\twr(X[i][0], X[i][1]);\n")
        w("\n\tif (!dry)\n\t\tprintf(\"fm6000_cminit: %d CM writes (replaces 47742 from the replay)\\n\", nwr);\n"
          "\treturn 0;\n}\n")

    tot = sum(len(r[6]) for r in blocks)
    print(f"{args.out}: {len(final)} CM registers")
    print(f"  {len(blocks)} arrays, "
          f"{sum(len(r[5]) for r in blocks)} distinct rows, "
          f"{len(leftover)} verbatim registers")


if __name__ == "__main__":
    main()
