#!/usr/bin/env python3
"""gen_sweepinit.py - emit fm6000_sweepinit.c: the L2F/LBS port sweep, in C.

fm6000_sweepgen.py proved (byte-exactly) that the 336-iteration loop is a sweep
over the port map. This turns that proof into a tool the switch can actually
run, the way gen_cminit.py did for CM -- the image has no Python.

WHY BOTH BLOCKS TOGETHER
    L2F is 56,127 writes but only 570 distinct registers: 426 three-word entries
    at 0x1a0c00 + 4*port, plus 144 profile words at 0x1a1000 + 0x10*k.

    It is tempting to just write those 570 and be done. Don't: each L2F entry in
    the sweep is paired with an LBS write at 0x014000 + port carrying
    (n << 16) | ~n, and the bisect showed that dropping LBS entirely leaves the
    switch with routes=1 and rx=0. The LBS write is very likely what commits the
    entry, so the pairing is reproduced rather than assumed away.

    Together: L2F 56,127 + LBS 18,547 = 74,674 replayed writes replaced.

INPUT
    sweep.json from `fm6000_sweepgen.py extract`, whose port_order is derived
    from our own board table (fm6000_serdes_ports.h), not from the trace.

Usage: gen_sweepinit.py <sweep.json> <replay.txt> -o fm6000_sweepinit.c
"""
import argparse
import json

L2F_BASE = 0x1A0C00
LBS_BASE = 0x014000
PROFILE_LO, PROFILE_HI = 0x1A1000, 0x1A1100


def in_block(a):
    return 0x180000 <= a < 0x200000 or LBS_BASE <= a < LBS_BASE + 0x1000


def leftover(replay, produced):
    """Every L2F/LBS register the sweep does NOT write.

    Both blocks carry configuration outside the port sweep -- the L2F profile
    words at 0x1a1000, and LBS registers from 0x014080 up. Emitting only the
    sweep leaves 269 registers unset, so the end state has to be completed from
    the trace. Computed rather than hand-listed, so it cannot silently drift.
    """
    final = {}
    for line in open(replay):
        p = line.split()
        if len(p) < 2:
            continue
        try:
            a, v = int(p[0], 16), int(p[1], 16)
        except ValueError:
            continue
        if in_block(a):
            final[a] = v
    return [(a, final[a]) for a in sorted(final) if produced.get(a) != final[a]]


def sweep_final(order, states, irregular, niter, it2s):
    """Simulate the generated sweep and return the state it LEAVES.

    Not just which addresses it touches: the trace re-writes some of them after
    the loop with different values (65 of them), so a coverage set alone leaves
    the end state wrong. Comparing against the simulated result catches those
    automatically instead of relying on a hand-maintained exception list.
    """
    st = {}
    for k in range(niter):
        if str(k) in irregular:
            for a, v in irregular[str(k)]:
                st[a] = v
            continue
        si = it2s.get(k)
        if si is None:
            continue
        vec = states[si]["vector"]
        prev = 0
        for i, port in enumerate(order):
            e = vec[i]
            st[L2F_BASE + 4 * prev] = e[0]
            st[L2F_BASE + 4 * prev + 1] = e[1]
            st[L2F_BASE + 4 * prev + 2] = e[2]
            n = i + 1
            st[LBS_BASE + port] = ((n << 16) | (~n & 0xFFFF)) & 0xFFFFFFFF
            prev = port
        if len(vec) > len(order):
            e = vec[len(order)]
            st[L2F_BASE + 4 * prev] = e[0]
            st[L2F_BASE + 4 * prev + 1] = e[1]
            st[L2F_BASE + 4 * prev + 2] = e[2]
        st[LBS_BASE] = 0xFF0000FF
    return st


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("sweep")
    ap.add_argument("replay")
    ap.add_argument("-o", "--out", default="fm6000_sweepinit.c")
    args = ap.parse_args()

    d = json.load(open(args.sweep))
    order = d["port_order"]
    states = d["states"]
    irregular = d["irregular"]
    # iteration -> state-vector index
    it2s = {}
    for si, s in enumerate(states):
        for k in s["iters"]:
            it2s[k] = si
    prof = leftover(args.replay,
                    sweep_final(order, states, irregular, d["iterations"], it2s))

    with open(args.out, "w") as f:
        w = f.write
        w("/* fm6000_sweepinit.c - run the FM6000's L2F/LBS port sweep ourselves.\n"
          " *\n"
          " * GENERATED by asic/fm6000/tools/gen_sweepinit.py -- do not edit by hand.\n"
          " *\n"
          " * Replaces 74,674 replayed writes (L2F 56,127 + LBS 18,547). The loop is\n"
          " * not a program: for each port, write its three-word L2F entry, then the\n"
          " * LBS index for the port whose entry comes next --\n"
          " *\n"
          " *     L2F  0x1a0c00 + 4*prev  <- 3-word entry\n"
          " *     LBS  0x014000 + port    <- (n << 16) | (~n & 0xffff)\n"
          " *\n"
          " * The one-step lag between them is what made the trace look unstructured.\n"
          " *\n"
          " * The LBS write is reproduced rather than dropped: the bisect showed that\n"
          " * removing LBS leaves the switch at routes=1, rx=0, so it is very likely the\n"
          " * commit for the L2F entry, not decoration.\n"
          " *\n"
          " * PORT_ORDER is derived from our own board table, not from the trace.\n"
          " * A few transition iterations are still carried verbatim.\n"
          " *\n"
          " * SPDX-License-Identifier: GPL-2.0-or-later */\n")
        w("#include <stdio.h>\n#include <stdlib.h>\n#include <fcntl.h>\n"
          "#include <unistd.h>\n#include <stdint.h>\n#include <string.h>\n"
          "#include <sys/mman.h>\n\n")
        w("#define L2F_BASE 0x%06xu\n#define LBS_BASE 0x%06xu\n"
          "#define NPORT    %d\n#define NITER    %d\n\n"
          % (L2F_BASE, LBS_BASE, len(order), d["iterations"]))

        w("static const unsigned char ORDER[NPORT] = { ")
        w(", ".join(str(p) for p in order))
        w(" };\n\n")

        # The recorded core is 55 steps: 54 ports plus a trailing L2F entry that
        # is closed by the LBS terminator at 0x014000. Size for all of it -- the
        # earlier byte-comparison stopped at 54 and never checked that tail.
        nstep = max(len(s["vector"]) for s in states)
        w("/* three-word L2F entry per step, one row per phase (NPORT + trailing) */\n")
        w("#define NSTEP %d\n" % nstep)
        w("static const uint32_t STATE[%d][NSTEP][3] = {\n" % len(states))
        for s in states:
            w("\t{\n")
            for e in s["vector"]:
                w("\t\t{ 0x%08x, 0x%08x, 0x%08x },\n" % tuple(e))
            w("\t},\n")
        w("};\n\n")

        w("/* iteration -> phase; -1 means the iteration is carried verbatim */\n")
        w("static const signed char PHASE[NITER] = { ")
        w(", ".join(str(it2s.get(k, -1)) for k in range(d["iterations"])))
        w(" };\n\n")

        keys = sorted(irregular, key=int)
        w("/* transition iterations we do not model yet */\n")
        for i, k in enumerate(keys):
            w("static const uint32_t V%d[][2] = {\n" % i)
            for a, v in irregular[k]:
                w("\t{ 0x%08x, 0x%08x },\n" % (a, v))
            w("};\n")
        w("static const struct { int iter; const uint32_t (*w)[2]; int n; } VERB[] = {\n")
        for i, k in enumerate(keys):
            w("\t{ %s, V%d, (int)(sizeof V%d / sizeof V%d[0]) },\n" % (k, i, i, i))
        w("};\n\n")

        w("/* L2F/LBS registers outside the sweep (profiles, LBS config) */\n")
        w("static const uint32_t PROF[][2] = {\n")
        for a, v in prof:
            w("\t{ 0x%08x, 0x%08x },\n" % (a, v))
        w("};\n\n")

        w("static volatile uint32_t *M;\nstatic int nwr, dry;\n\n"
          "static void wr(unsigned a, uint32_t v)\n{\n"
          "\tif (dry) printf(\"%08x %08x\\n\", a, v);\n"
          "\telse { M[a] = v; __sync_synchronize(); }\n\tnwr++;\n}\n\n")

        w("int main(int argc, char **argv)\n{\n"
          "\tconst char *bdf = \"0000:02:00.0\";\n"
          "\tchar p[256];\n\tint fd, k, i, j, prev, n;\n\n"
          "\tfor (i = 1; i < argc; i++) {\n"
          "\t\tif (!strcmp(argv[i], \"-n\")) dry = 1;\n\t\telse bdf = argv[i];\n\t}\n"
          "\tif (!dry) {\n"
          "\t\tsnprintf(p, sizeof p, \"/sys/bus/pci/devices/%s/resource0\", bdf);\n"
          "\t\tfd = open(p, O_RDWR | O_SYNC);\n"
          "\t\tif (fd < 0) { perror(\"open\"); return 1; }\n"
          "\t\tM = mmap(NULL, 32u*1024*1024, PROT_READ|PROT_WRITE, MAP_SHARED, fd, 0);\n"
          "\t\tif (M == MAP_FAILED) { perror(\"mmap\"); return 1; }\n\t}\n\n"
          "\tfor (k = 0; k < NITER; k++) {\n"
          "\t\tint done = 0;\n"
          "\t\tfor (i = 0; i < (int)(sizeof VERB / sizeof VERB[0]); i++)\n"
          "\t\t\tif (VERB[i].iter == k) {\n"
          "\t\t\t\tfor (j = 0; j < VERB[i].n; j++)\n"
          "\t\t\t\t\twr(VERB[i].w[j][0], VERB[i].w[j][1]);\n"
          "\t\t\t\tdone = 1; break;\n\t\t\t}\n"
          "\t\tif (done || PHASE[k] < 0) continue;\n"
          "\t\tprev = 0;\n"
          "\t\tfor (i = 0; i < NPORT; i++) {\n"
          "\t\t\twr(L2F_BASE + 4*prev,     STATE[PHASE[k]][i][0]);\n"
          "\t\t\twr(L2F_BASE + 4*prev + 1, STATE[PHASE[k]][i][1]);\n"
          "\t\t\twr(L2F_BASE + 4*prev + 2, STATE[PHASE[k]][i][2]);\n"
          "\t\t\tn = i + 1;\n"
          "\t\t\twr(LBS_BASE + ORDER[i], ((uint32_t)n << 16) | (~(uint32_t)n & 0xffff));\n"
          "\t\t\tprev = ORDER[i];\n\t\t}\n"
          "\t\t/* trailing entry, closed by the LBS terminator */\n"
          "\t\tif (NSTEP > NPORT) {\n"
          "\t\t\twr(L2F_BASE + 4*prev,     STATE[PHASE[k]][NPORT][0]);\n"
          "\t\t\twr(L2F_BASE + 4*prev + 1, STATE[PHASE[k]][NPORT][1]);\n"
          "\t\t\twr(L2F_BASE + 4*prev + 2, STATE[PHASE[k]][NPORT][2]);\n"
          "\t\t}\n"
          "\t\twr(LBS_BASE, 0xff0000ffu);\n\t}\n"
          "\tfor (i = 0; i < (int)(sizeof PROF / sizeof PROF[0]); i++)\n"
          "\t\twr(PROF[i][0], PROF[i][1]);\n\n"
          "\tif (!dry)\n\t\tprintf(\"fm6000_sweepinit: %d writes (replaces 74674 from the replay)\\n\", nwr);\n"
          "\treturn 0;\n}\n")

    print(f"{args.out}: {len(order)} ports, {len(states)} phases, "
          f"{len(keys)} verbatim iterations, {len(prof)} profile words")


if __name__ == "__main__":
    main()
