#!/usr/bin/env python3
"""gen_safmatrix.py - author SAF_MATRIX, the store-and-forward port matrix.

★ WHY THIS ONE MATTERS OUT OF PROPORTION TO ITS SIZE. SAF_MATRIX is **74% of
everything the vendor replay still supplies**: 34,668 of the 46,611 writes no
generator covered, over just 168 addresses. `fm6000_safinit` writes NOTHING in
this range -- the whole matrix came from the replay.

It is 76 entries of 3 words (96 bits) at 0x0a0000, pitch pow2ceil(3) = 4, and the
96 bits are a PORT BITMAP: entry p holds the set of ports p may store-and-forward
with.

★ THE REASON IT IS WRITTEN 34,668 TIMES IS THAT IT TRACKS LINK STATE. Entry 20
(et2) alone is written 654 times, but across those it takes only **13 distinct
values**, building up as ports come up and collapsing back at the end. The final
state has just **four distinct values across 56 entries**:

    ports 0, 2        every bit set
    port 1            bits 0..81
    ports 3, 20, 40   {0, 1, 2}                 <- the ports with a transceiver
    other 50 front    {0, 1, 2, 3} | {20, 40}   <- CPU/mgmt ports + the linked ports

Ports 20 and 40 are et2 and et1 (established independently from
PARSER_INIT_FIELDS), and port 3 is the third SFP cage. So the rule is: a port
that is UP is allowed the CPU ports only, and a port that is DOWN is allowed the
CPU ports plus whichever ports are up.

⚠ THIS IS CONFIG-DEPENDENT, AND THAT IS THE POINT. LINKED_PORTS below is the
state-machine input: change which cages have a link and this matrix changes. This
generator emits the CONVERGED state for the current cabling rather than modelling
the transitions. That is enough if the intermediate states are transient -- which
is exactly what it is here to test.

⚠ The SDK field map mis-associates this register (it reports PORT_STATUS's fields
for it), so the bit meanings below are read off the values, not taken from
sdk_fieldmap.py. Do not trust `sdk_fieldmap.py --reg SAF_MATRIX`.

usage:
    gen_safmatrix.py --emit | --addrs | --structure | --verify <img> | --c FILE
SPDX-License-Identifier: GPL-2.0-or-later
"""
import argparse
import sys

sys.path.insert(0, __file__.rsplit("/", 1)[0])
from parser_decode import load  # noqa: E402

BASE, WORDS, PITCH, N_PORTS = 0x0A0000, 3, 4, 76

ACTIVE_PORTS = [0, 1, 3] + list(range(20, 48)) + list(range(52, 76))
CPU_PORTS = [0, 1, 2, 3]          # note 2, which is not in the configured set
FRONT_PANEL = [p for p in ACTIVE_PORTS if p not in (0, 1, 3)]

# ★ The state-machine input: cages with a link partner. et2 = 20, et1 = 40,
# and 3 is the third SFP. Change the cabling and this changes.
LINKED_PORTS = [3, 20, 40]

FULL = (1 << 96) - 1
PORT1_MASK = (1 << 82) - 1        # observed: bits 0..81


def mask_for(p):
    if p in (0, 2):
        return FULL
    if p == 1:
        return PORT1_MASK
    if p in LINKED_PORTS:
        return 0b111                                   # the CPU ports only
    m = 0
    for c in (0, 1, 2, 3):
        m |= 1 << c
    for c in LINKED_PORTS:
        if c > 3:
            m |= 1 << c
    return m


def entries():
    """The 56 entries the replay converges: CPU/mgmt ports plus the front panel."""
    return sorted(set([0, 1, 2, 3] + FRONT_PANEL))


def build_seq():
    seq = []
    for p in entries():
        m = mask_for(p)
        for w in range(WORDS):
            seq.append((BASE + p * PITCH + w, (m >> (32 * w)) & 0xFFFFFFFF))
    return seq


def build():
    return {a: v for a, v in build_seq()}


def structure():
    import collections
    g = collections.defaultdict(list)
    for p in entries():
        g[mask_for(p)].append(p)
    print(f"SAF_MATRIX  0x{BASE:06x}  {N_PORTS} entries x {WORDS} words "
          f"(pitch {PITCH})")
    print(f"linked ports: {LINKED_PORTS}")
    for m, ports in sorted(g.items(), key=lambda kv: -len(kv[1])):
        bits = [b for b in range(96) if m >> b & 1]
        shown = bits if len(bits) <= 8 else f"{len(bits)} bits"
        print(f"  {len(ports):2d} entries -> {shown}")
    print(f"\ntotal {len(build_seq())} writes over {len(build())} addresses")
    return 0


def verify(image):
    eos, ours = load(image), build()
    same = bad = missing = 0
    for a in sorted(ours):
        e = eos.get(a)
        if e is None:
            missing += 1
        elif e == ours[a]:
            same += 1
        else:
            if bad < 8:
                print(f"  0x{a:06x}  eos={e:08x}  ours={ours[a]:08x}")
            bad += 1
    print(f"identical {same}, differing {bad}, absent {missing}")
    ok = bad == 0 and missing == 0
    print("VERIFY PASS" if ok else "VERIFY FAIL")
    return 0 if ok else 1


C_HEAD = r"""/* fm6000_safmatrix.c - SAF_MATRIX, the store-and-forward port matrix.
 *
 * GENERATED by asic/fm6000/tools/gen_safmatrix.py --c. Edit the generator.
 *
 * 76 entries x 3 words at 0x0a0000 (pitch 4). The 96 bits are a PORT BITMAP:
 * entry p is the set of ports p may store-and-forward with.
 *
 * This is 74% of everything the vendor replay still supplied -- 34,668 writes
 * over 168 addresses -- because it TRACKS LINK STATE and is rewritten as ports
 * come up. Its converged state is only four distinct values:
 *
 *   ports 0, 2        all bits
 *   port 1            bits 0..81
 *   ports 3, 20, 40   {0,1,2}                  the cages with a transceiver
 *   other 50 front    {0,1,2,3} | {20,40}      CPU/mgmt ports + the linked ports
 *
 * ⚠ CONFIG-DEPENDENT. Ports 20 and 40 are et2 and et1. Change which cages have a
 * link and this matrix changes -- regenerate rather than assuming.
 *
 * usage: fm6000_safmatrix [-n | -a] [-b bdf]
 * SPDX-License-Identifier: GPL-2.0-or-later */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdint.h>
#include <sys/mman.h>

static const struct { uint32_t addr, val; } W[] = {
"""

C_TAIL = r"""};

static volatile uint32_t *M;

int main(int argc, char **argv)
{
	const char *bdf = "0000:02:00.0";
	int dry = 0, list = 0, i;

	for (i = 1; i < argc; i++) {
		if      (!strcmp(argv[i], "-n")) dry = 1;
		else if (!strcmp(argv[i], "-a")) list = 1;
		else if (!strcmp(argv[i], "-b") && i + 1 < argc) bdf = argv[++i];
		else { fprintf(stderr, "usage: %s [-n|-a] [-b bdf]\n", argv[0]); return 2; }
	}

	if (!dry && !list) {
		char path[256];
		snprintf(path, sizeof path, "/sys/bus/pci/devices/%s/resource0", bdf);
		int fd = open(path, O_RDWR | O_SYNC);
		if (fd < 0) { perror("open resource0"); return 1; }
		M = mmap(NULL, 32u * 1024 * 1024, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
		if (M == MAP_FAILED) { perror("mmap"); return 1; }
	}

	for (i = 0; i < (int)(sizeof W / sizeof W[0]); i++) {
		if (list)      printf("%08x\n", W[i].addr);
		else if (dry)  printf("%08x %08x\n", W[i].addr, W[i].val);
		else         { M[W[i].addr] = W[i].val; __sync_synchronize(); }
	}
	if (!dry && !list)
		fprintf(stderr, "fm6000_safmatrix: %d writes\n",
		        (int)(sizeof W / sizeof W[0]));
	return 0;
}
"""


def emit_c(path):
    seq = build_seq()
    with open(path, "w") as f:
        f.write(C_HEAD)
        for a, v in seq:
            f.write("\t{ 0x%06x, 0x%08x },\n" % (a, v))
        f.write(C_TAIL)
    print("wrote %s: %d writes" % (path, len(seq)), file=sys.stderr)
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--emit", action="store_true")
    ap.add_argument("--addrs", action="store_true")
    ap.add_argument("--structure", action="store_true")
    ap.add_argument("--verify")
    ap.add_argument("--c")
    a = ap.parse_args()
    if a.structure:
        return structure()
    if a.verify:
        return verify(a.verify)
    if a.c:
        return emit_c(a.c)
    for ad, v in build_seq():
        print(f"{ad:08x}" if a.addrs else f"{ad:08x} {v:08x}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
