#!/usr/bin/env python3
"""gen_tableinit.py - emit the fm6000_*init.c block generators from a replay.

One script for every block whose configuration is TABLE STATE rather than a
bring-up procedure. It replaces four ad-hoc heredocs that produced
fm6000_ffuinit.c, fm6000_l2linit.c, fm6000_l2finit.c and fm6000_eplinit.c --
those files carried "GENERATED by ..." headers naming scripts that did not
exist, so they could not actually be regenerated. They can now.

WHICH BLOCKS THIS WORKS FOR -- AND WHY THE STATISTICS DO NOT TELL YOU

    ⚠ An earlier version of this file claimed the write-once fraction predicts
    collapsibility. IT DOES NOT. Measured against what actually works:

        block  writes  once/write  transitions   collapses?
        saf     34668       0.5%         8.9%    yes
        cm      47742      17.1%        89.1%    yes
        l2f     56127       0.6%         1.7%    yes
        l2l     24620      99.8%        99.9%    yes
        ffu     14549      59.7%        89.2%    yes (table only)
        epl     22051       1.9%        36.6%    NO -- wedges the chip

    Neither column separates EPL from the rest: L2F is *less* write-once than
    EPL and collapses fine; CM has a *higher* transition rate than EPL and
    collapses fine.

    The real distinction is SEMANTIC. A block collapses if it holds table state
    the pipeline reads (SAF, CM, L2F, L2L, FFU). It does not collapse if its
    writes drive hardware through a sequence -- EPL is the SerDes/PCS bring-up,
    where the intermediate states are the point. No statistic we tried
    distinguishes those; you have to know what the block is for.

    What --survey IS good for: choosing the MODE below, and spotting strobes.

TWO MODES, because blocks differ in kind
    --mode once   emit only registers written exactly once, and print their
                  addresses with -a so the boot script can filter precisely
                  those lines. Multi-write control registers stay in the replay
                  with their sequences intact. Required wherever a block mixes
                  table and control: the FFU has a commit strobe at 0x3f0000
                  pulsed 59 times, and one commit instead of 59 means the
                  CPU-punt traps never apply.
    --mode final  emit the end state of every register in the range. Only safe
                  where nothing in the range is a strobe (L2F/LBS).
    --mode seq    emit EVERY write in the RECORDED ORDER -- no reduction. For
                  blocks that drive hardware through a sequence, where the
                  intermediate states ARE the point: collapsing EPL wedges the
                  chip, relocating its sequence works. Buys no write-count
                  reduction; it moves the block out of EOS's file, which is the
                  actual goal.

PLACEMENT is chosen in fm6000-fullseq.sh, not here, and it is per-block:
CM/SAF hoist to their first in-loop write; L2F/LBS only works written AFTER the
whole loop. See docs/EDGENOS-7150.md (was SELF-CONTAINED-PLAN).

Usage:
    gen_tableinit.py <replay.txt> --survey
    gen_tableinit.py <replay.txt> --name ffu --range 300000-400000 --mode once \\
                     -o fm6000_ffuinit.c
"""
import argparse
import collections
import sys

# The blocks generated today, so `--survey` and the build can agree on ranges.
KNOWN = {
    "ffu":  (0x300000, 0x400000, "once",  "FFU: TCAM, action SRAM, routing prefix/action arrays"),
    "l2l":  (0x030000, 0x038000, "once",  "L2L: the L2 lookup table"),
    "l2f":  (0x180000, 0x200000, "final", "L2F + LBS: port map and load-balance state"),
    "epl":  (0x0E0000, 0x100000, "once",  "EPL: per-port SerDes/PCS -- A PROCEDURE, does not work"),
    # Second tranche. All lookup state the pipeline reads, which is the
    # category that collapses; PARSER/MOD/L2AR are TCAM + action SRAM.
    "l2ar":   (0x140000, 0x150000, "once", "L2AR: L2 action resolution (TCAM + action SRAM)"),
    "parser": (0x100000, 0x110000, "once", "PARSER: protocol CAM + action SRAM, 28 slices"),
    "mod":    (0x150000, 0x160000, "once", "MOD: egress modification routines"),
    "l3ar":   (0x010000, 0x014000, "once", "L3AR: L3 action resolution"),
    "hash":   (0x00B000, 0x00C000, "once", "HASH: hash/ECMP selection config"),
    "mapper": (0x120000, 0x130000, "once", "MAPPER: field mapping tables"),
    # Sequence blocks -- relocate, never collapse.
    "eplseq":  (0x0E0000, 0x100000, "seq", "EPL: per-port SerDes/PCS bring-up"),
    "l2arseq": (0x140000, 0x150000, "seq", "L2AR: L2 action resolution, 84% multi-write"),
    # Small control blocks, surveyed 2026-08-08.
    "mgmt2":   (0x01C000, 0x020000, "once", "MGMT2: management/control registers"),
    "sweeper": (0x00D000, 0x00E000, "once", "L2L_SWEEPER: L2 table ageing sweeper"),
    "cmm":     (0x020000, 0x028000, "once", "CMM: congestion management manager"),
    "monitor": (0x003000, 0x004000, "once", "MONITOR: monitoring/mirroring control"),
    "statsar": (0x018000, 0x01A000, "once", "STATS_AR: statistics action resolution"),
    "eacl":    (0x006000, 0x007000, "once", "EACL: egress ACL"),
    "lag":     (0x007000, 0x008000, "once", "LAG: link aggregation"),
    "glort":   (0x00E000, 0x00F000, "once", "GLORT: global resource tags"),
}


def load(path, lo, hi):
    rows = []
    for line in open(path):
        p = line.split()
        if len(p) < 2:
            continue
        try:
            a, v = int(p[0], 16), int(p[1], 16)
        except ValueError:
            continue
        if lo <= a < hi:
            rows.append((a, v))
    return rows


def survey(path):
    # Reports shape, NOT a verdict on collapsibility -- see the module
    # docstring: no statistic here separates EPL (wedges) from L2F (fine).
    # Use it to pick --mode and to notice strobes, then decide from what the
    # block actually does.
    print(f"{'block':<8}{'writes':>9}{'regs':>9}{'once/reg':>10}{'once/WRITE':>12}   verdict")
    for name, (lo, hi, _, _) in KNOWN.items():
        rows = load(path, lo, hi)
        if not rows:
            continue
        c = collections.Counter(a for a, _ in rows)
        once = sum(1 for a in c if c[a] == 1)
        fw = once / len(rows)
        # suggests a MODE only; collapsibility is a semantic question
        verdict = ("--mode once (mostly write-once)" if fw > 0.75 else
                   "--mode once (mixed table/control)" if fw > 0.25 else
                   "--mode final, IF it is a table at all")
        print(f"{name:<8}{len(rows):>9}{len(c):>9}{once/len(c):>9.1%}"
              f"{fw:>11.1%}   {verdict}")


C_SEQ_HEAD = """/* %(tool)s.c - replay the %(NAME)s bring-up SEQUENCE, in order.
 *
 * GENERATED by asic/fm6000/tools/gen_tableinit.py --mode seq -- do not edit.
 *
 * %(note)s
 *
 * %(nw)d writes over %(nr)d registers, emitted in the RECORDED ORDER and NOT
 * reduced. This block drives hardware through a sequence -- its intermediate
 * states are the point -- so it cannot be collapsed to an end state; doing that
 * to EPL wedges the chip. It CAN be relocated, which is what this is for.
 * No write-count saving: the win is that the block leaves EOS's file.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later */
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdint.h>
#include <string.h>
#include <sys/mman.h>

static const uint32_t A[] = {
"""

C_SEQ_TAIL = """};

int main(int argc, char **argv)
{
\tconst char *bdf = "0000:02:00.0";
\tchar p[256]; int fd, i, dry = 0, list = 0;
\tvolatile uint32_t *M = NULL;

\tfor (i = 1; i < argc; i++) {
\t\tif (!strcmp(argv[i], "-n")) dry = 1;
\t\telse if (!strcmp(argv[i], "-a")) list = 1;
\t\telse bdf = argv[i];
\t}
\tif (list) {
\t\tfor (i = 0; i < (int)(sizeof A / sizeof A[0]); i++) printf("%08x\\n", A[i]);
\t\treturn 0;
\t}
\tif (!dry) {
\t\tsnprintf(p, sizeof p, "/sys/bus/pci/devices/%s/resource0", bdf);
\t\tfd = open(p, O_RDWR | O_SYNC);
\t\tif (fd < 0) { perror("open"); return 1; }
\t\tM = mmap(NULL, 32u*1024*1024, PROT_READ|PROT_WRITE, MAP_SHARED, fd, 0);
\t\tif (M == MAP_FAILED) { perror("mmap"); return 1; }
\t}
\tfor (i = 0; i < (int)(sizeof S / sizeof S[0]); i++) {
\t\tif (dry) printf("%08x %08x\\n", S[i][0], S[i][1]);
\t\telse { M[S[i][0]] = S[i][1]; __sync_synchronize(); }
\t}
\tif (!dry) printf("SEQTOOL: %d writes replayed in order\\n",
\t                 (int)(sizeof S / sizeof S[0]));
\treturn 0;
}
"""


def emit_seq(rows, name, out, note):
    tool = "fm6000_" + name
    addrs = sorted({a for a, _ in rows})
    with open(out, "w") as f:
        f.write(C_SEQ_HEAD % {"tool": tool, "NAME": name.upper(), "note": note,
                              "nw": len(rows), "nr": len(addrs)})
        for a in addrs:
            f.write("\t0x%08x,\n" % a)
        f.write("};\n\nstatic const uint32_t S[][2] = {\n")
        for a, v in rows:
            f.write("\t{0x%08x,0x%08x},\n" % (a, v))
        f.write(C_SEQ_TAIL.replace("SEQTOOL", tool))
    print("%s: %d writes over %d registers (sequence, in order)"
          % (out, len(rows), len(addrs)))


def emit(path, name, lo, hi, mode, out, note):
    rows = load(path, lo, hi)
    if not rows:
        sys.exit(f"{path}: no writes in {lo:#x}-{hi:#x}")
    c = collections.Counter(a for a, _ in rows)
    if mode == "seq":
        return emit_seq(rows, name, out, note)
    if mode == "once":
        sel = {a: v for a, v in rows if c[a] == 1}
        kept = len(c) - len(sel)
    else:
        sel = {}
        for a, v in rows:
            sel[a] = v
        kept = 0
    nz = sum(1 for v in sel.values() if v)
    tool = f"fm6000_{name}init"

    with open(out, "w") as f:
        f.write(f"""/* {tool}.c - program the {name.upper()} block ourselves.
 *
 * GENERATED by asic/fm6000/tools/gen_tableinit.py -- do not edit by hand.
 *   gen_tableinit.py <replay> --name {name} --range {lo:06x}-{hi:06x} --mode {mode}
 *
 * {note}
 *
 * Replaces {len(rows)} replayed writes with {len(sel)} ({nz} non-zero).
""")
        if mode == "once":
            f.write(f""" *
 * TABLE ONLY, deliberately: emits the {len(sel)} registers written exactly once
 * and leaves the {kept} multi-write control registers in the replay with their
 * sequences intact. Collapsing those would destroy strobes -- the FFU's commit
 * pulse at 0x3f0000 fires 59 times, and one commit instead of 59 means the
 * CPU-punt traps never apply. `-a` prints the address list so the boot script
 * filters exactly these lines and nothing else.
""")
        f.write(""" *
 * SPDX-License-Identifier: GPL-2.0-or-later */
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdint.h>
#include <string.h>
#include <sys/mman.h>

static const uint32_t R[][2] = {
""")
        for a in sorted(sel):
            f.write("\t{0x%08x,0x%08x},\n" % (a, sel[a]))
        f.write("""};

int main(int argc, char **argv)
{
\tconst char *bdf = "0000:02:00.0";
\tchar p[256]; int fd, i, dry = 0, list = 0;
\tvolatile uint32_t *M = NULL;

\tfor (i = 1; i < argc; i++) {
\t\tif (!strcmp(argv[i], "-n")) dry = 1;
\t\telse if (!strcmp(argv[i], "-a")) list = 1;
\t\telse bdf = argv[i];
\t}
\tif (list) {
\t\tfor (i = 0; i < (int)(sizeof R / sizeof R[0]); i++)
\t\t\tprintf("%08x\\n", R[i][0]);
\t\treturn 0;
\t}
\tif (!dry) {
\t\tsnprintf(p, sizeof p, "/sys/bus/pci/devices/%s/resource0", bdf);
\t\tfd = open(p, O_RDWR | O_SYNC);
\t\tif (fd < 0) { perror("open"); return 1; }
\t\tM = mmap(NULL, 32u*1024*1024, PROT_READ|PROT_WRITE, MAP_SHARED, fd, 0);
\t\tif (M == MAP_FAILED) { perror("mmap"); return 1; }
\t}
\tfor (i = 0; i < (int)(sizeof R / sizeof R[0]); i++) {
\t\tif (dry) printf("%08x %08x\\n", R[i][0], R[i][1]);
\t\telse { M[R[i][0]] = R[i][1]; __sync_synchronize(); }
\t}
""")
        f.write(f'\tif (!dry)\n\t\tprintf("{tool}: %d writes\\n",\n'
                '\t\t       (int)(sizeof R / sizeof R[0]));\n\treturn 0;\n}\n')
    print(f"{out}: {len(sel)} registers from {len(rows)} writes "
          f"({kept} multi-write left in the replay)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("replay")
    ap.add_argument("--survey", action="store_true")
    ap.add_argument("--name")
    ap.add_argument("--range")
    ap.add_argument("--mode", choices=["once", "final", "seq"])
    ap.add_argument("-o", "--out")
    a = ap.parse_args()

    if a.survey:
        survey(a.replay)
        return
    if not (a.name and a.out):
        sys.exit("need --name and -o (or --survey)")
    if a.range:
        lo, hi = (int(x, 16) for x in a.range.split("-"))
        mode = a.mode or "once"
        note = KNOWN.get(a.name, (0, 0, "", ""))[3] or f"{a.name.upper()} block"
    else:
        lo, hi, mode, note = KNOWN[a.name]
        mode = a.mode or mode
    emit(a.replay, a.name, lo, hi, mode, a.out, note)


if __name__ == "__main__":
    main()
