#!/usr/bin/env python3
"""replay_classify.py - classify every write in an FM6000 boot replay.

The replay set is the last thing standing between EdgeNOS and a self-contained
release: it is a transcription of EOS configuring the chip, so we cannot ship it.
Replacing it means generating each part ourselves. This tool says exactly how big
each part is, and which are already solved.

Categories, and what replaces each:

  ZEROFILL     writes of 0 into table memory -- already generated by
               fm6000_memfill (129 fills, 1.14M words). SOLVED.
  SPICO_FW     the SerDes SPICO firmware upload (SBus receiver 0xFD regs
               0x04-0x07). Intel's code. Extractable but not redistributable;
               operator-supplied, or dropped where the media allows.
  MICROCODE    parser / L2AR / MOD. NOT opaque code -- TCAM + action SRAM with a
               published encoding (datasheet Table 5-3). Generate from a
               protocol description. The whole parser is ~2,117 CAM entries.
  SBUS_TUNE    per-lane SerDes tuning over SBus. Small. Board measurement.
  CONFIG       everything else: GLORT, dmask, NEXTHOP, EPL, CM, SAF, scheduler.
               Facts about how to configure the chip -- generate from a
               declarative platform description.

Usage:
    replay_classify.py <replay.txt> [--ucode-addrs FILE] [--dump CATEGORY]
"""
import argparse
import collections
import sys

# word-address ranges, from fm6000_api_regs_int.h / docs/EDGENOS-7150.md (was ROUTING-FIB)
# Block address map. These are the chip's top-level base/size pairs -- interface
# facts, each one independently confirmable from our own traces by where writes
# actually cluster. An earlier hand-guessed version of this table was wrong in
# several places (it invented an "MA_TABLE" at 0x1A0000, which is really L2F).
BLOCKS = [
    (0x000000, 0x001000, "MGMT1"), (0x001000, 0x002000, "PCIE"),
    (0x002000, 0x003000, "ESCHED"), (0x003000, 0x004000, "MONITOR"),
    (0x004000, 0x005000, "MSB"), (0x005000, 0x006000, "FIBM"),
    (0x006000, 0x007000, "EACL"), (0x007000, 0x008000, "LAG"),
    (0x008000, 0x009000, "SSCHED"), (0x00B000, 0x00C000, "HASH"),
    (0x00C000, 0x00D000, "ALU"), (0x00D000, 0x00E000, "L2L_SWEEPER"),
    (0x00E000, 0x00F000, "GLORT"), (0x00F000, 0x010000, "JSS"),
    (0x010000, 0x014000, "L3AR"), (0x014000, 0x015000, "LBS"),
    (0x018000, 0x01A000, "STATS_AR"), (0x01A000, 0x01B000, "STATS_DISCRETE"),
    (0x01C000, 0x020000, "MGMT2"), (0x020000, 0x028000, "CMM"),
    (0x028000, 0x029000, "FC_BEM"), (0x030000, 0x038000, "L2L"),
    (0x0A0000, 0x0A1000, "SAF"), (0x0B0500, 0x0C0500, "SERDES_ETH_WRITE"),
    (0x0C0500, 0x0D0500, "SERDES_ETH_READ"), (0x0D1100, 0x0D1500, "SERDES_PCIE_WRITE"),
    (0x0D2100, 0x0D2500, "SERDES_PCIE_READ"), (0x0E0000, 0x100000, "EPL"),
    (0x100000, 0x110000, "PARSER"), (0x110000, 0x120000, "CM"),
    (0x120000, 0x130000, "MAPPER"), (0x130000, 0x140000, "POLICERS"),
    (0x140000, 0x150000, "L2AR"), (0x150000, 0x160000, "MOD"),
    (0x160000, 0x180000, "NEXTHOP"), (0x180000, 0x200000, "L2F"),
    (0x200000, 0x240000, "STATS_BANK"), (0x240000, 0x260000, "MCAST_MID"),
    (0x260000, 0x280000, "MCAST_POST"), (0x280000, 0x300000, "L2L_MAC"),
    (0x300000, 0x400000, "FFU"),
]


def block_of(addr):
    for lo, hi, name in BLOCKS:
        if lo <= addr < hi:
            return name
    return "other"


def load_ucode_addrs(path):
    if not path:
        return set()
    try:
        return {int(l, 16) for l in open(path) if l.strip()}
    except OSError:
        print(f"warning: cannot read {path}; microcode will be range-guessed",
              file=sys.stderr)
        return set()


def classify(path, ucode_addrs):
    rows = []
    pending = None
    for line in open(path):
        p = line.split()
        if len(p) < 2:
            continue
        try:
            a, v = int(p[0], 16), int(p[1], 16)
        except ValueError:
            continue

        if a == 0xF002:
            pending = v
            rows.append((a, v, "SBUS_TUNE"))       # provisional; fixed up below
            continue
        if a == 0xF001:
            # SBus command: Receiver[15:8], Register[7:0], Exec[24]
            if (v >> 24) & 1 and ((v >> 8) & 0xFF) == 0xFD and (v & 0xFF) in (4, 5, 6, 7):
                rows.append((a, v, "SPICO_FW"))
            else:
                rows.append((a, v, "SBUS_TUNE"))
            continue

        if a in ucode_addrs:
            rows.append((a, v, "MICROCODE"))
        elif v == 0:
            rows.append((a, v, "ZERO?"))       # resolved below -- see fill detection
        else:
            rows.append((a, v, "CONFIG"))

    # Resolve ZERO?. A write of 0 is only "fill" when it is part of a run of
    # consecutive addresses being cleared back-to-back; an ISOLATED zero write is
    # a control register being deliberately set to 0, which is real configuration.
    #
    # This distinction is not academic: a replay with ALL zero-writes removed
    # still trains the link but forwards nothing (+0 vs +60 on the same boot),
    # because 92% of them turn out to be isolated config, not fill.
    RUN_MIN = 8
    zi = [i for i, (a, v, c) in enumerate(rows) if c == "ZERO?"]
    run_start = 0
    for k in range(1, len(zi) + 1):
        end_of_run = (k == len(zi) or
                      zi[k] != zi[k - 1] + 1 or
                      rows[zi[k]][0] != rows[zi[k - 1]][0] + 1)
        if end_of_run:
            label = "ZEROFILL" if (k - run_start) >= RUN_MIN else "CONFIG"
            for j in zi[run_start:k]:
                a, v, _ = rows[j]
                rows[j] = (a, v, label)
            run_start = k

    # One SBus transaction is three writes: F002 <data>, F001 <- 0 (clear), then
    # F001 <- cmd (Exec set). Only the last carries the receiver/register, so the
    # first two must be attributed to it or the firmware upload is undercounted
    # by two thirds and shows up as "tuning".
    for i, (a, v, c) in enumerate(rows):
        if a in (0xF002, 0xF001) and not (a == 0xF001 and (v >> 24) & 1):
            for j in range(i + 1, min(i + 4, len(rows))):
                if rows[j][0] == 0xF001 and (rows[j][1] >> 24) & 1:
                    rows[i] = (a, v, rows[j][2])
                    break
    return rows


REPLACEMENT = {
    "ZEROFILL":  "fm6000_memfill (DONE)",
    "SPICO_FW":  "operator-supplied, or drop (media-dependent)",
    "MICROCODE": "generator from a protocol description (TCAM + action SRAM)",
    "SBUS_TUNE": "board measurement / per-lane table",
    "CONFIG":    "generator from a declarative platform description",
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("replay")
    ap.add_argument("--ucode-addrs")
    ap.add_argument("--dump", help="print every write in this category")
    args = ap.parse_args()

    rows = classify(args.replay, load_ucode_addrs(args.ucode_addrs))
    total = len(rows)
    cats = collections.Counter(c for _, _, c in rows)

    print(f"{args.replay}: {total} writes\n")
    print(f"  {'category':<11} {'writes':>8} {'share':>7}   replaced by")
    print(f"  {'-'*11} {'-'*8} {'-'*7}   {'-'*44}")
    for c, n in cats.most_common():
        print(f"  {c:<11} {n:>8} {100*n/total:>6.1f}%   {REPLACEMENT.get(c,'?')}")

    done = cats["ZEROFILL"]
    todo = cats["MICROCODE"] + cats["CONFIG"] + cats["SBUS_TUNE"]
    print(f"\n  already generated by our own code : {done:>8} ({100*done/total:.1f}%)")
    print(f"  still to be generated             : {todo:>8} ({100*todo/total:.1f}%)")
    print(f"  third-party firmware              : {cats['SPICO_FW']:>8} "
          f"({100*cats['SPICO_FW']/total:.1f}%)")

    print("\n  CONFIG by register block (what a config generator must emit):")
    cfg = collections.Counter(block_of(a) for a, _, c in rows if c == "CONFIG")
    for b, n in cfg.most_common(12):
        print(f"    {b:<12} {n:>7}")

    print("\n  MICROCODE by block:")
    uc = collections.Counter(block_of(a) for a, _, c in rows if c == "MICROCODE")
    for b, n in uc.most_common():
        print(f"    {b:<12} {n:>7}")

    if args.dump:
        for a, v, c in rows:
            if c == args.dump:
                print(f"{a:08x} {v:08x}")


if __name__ == "__main__":
    main()
