/* fm6000_cmminit.c - program the CMM block ourselves.
 *
 * GENERATED by asic/fm6000/tools/gen_tableinit.py -- do not edit by hand.
 *   gen_tableinit.py <replay> --name cmm --range 020000-028000 --mode once
 *
 * CMM: congestion management manager
 *
 * Replaces 1344 replayed writes with 72 (72 non-zero).
 *
 * TABLE ONLY, deliberately: emits the 72 registers written exactly once
 * and leaves the 636 multi-write control registers in the replay with their
 * sequences intact. Collapsing those would destroy strobes -- the FFU's commit
 * pulse at 0x3f0000 fires 59 times, and one commit instead of 59 means the
 * CPU-punt traps never apply. `-a` prints the address list so the boot script
 * filters exactly these lines and nothing else.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later */
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdint.h>
#include <string.h>
#include <sys/mman.h>

static const uint32_t R[][2] = {
	{0x00022080,0xffffffff},
	{0x00022081,0xffffffff},
	{0x00022082,0xffffffff},
	{0x00022084,0xffffffff},
	{0x00022085,0xffffffff},
	{0x00022086,0xffffffff},
	{0x00022088,0xffffffff},
	{0x00022089,0xffffffff},
	{0x0002208a,0xffffffff},
	{0x0002208c,0xffffffff},
	{0x0002208d,0xffffffff},
	{0x0002208e,0xffffffff},
	{0x00022090,0xffffffff},
	{0x00022091,0xffffffff},
	{0x00022092,0xffffffff},
	{0x00022094,0xffffffff},
	{0x00022095,0xffffffff},
	{0x00022096,0xffffffff},
	{0x00022098,0xffffffff},
	{0x00022099,0xffffffff},
	{0x0002209a,0xffffffff},
	{0x0002209c,0xffffffff},
	{0x0002209d,0xffffffff},
	{0x0002209e,0xffffffff},
	{0x000220a0,0xffffffff},
	{0x000220a1,0xffffffff},
	{0x000220a2,0xffffffff},
	{0x000220a4,0xffffffff},
	{0x000220a5,0xffffffff},
	{0x000220a6,0xffffffff},
	{0x000220a8,0xffffffff},
	{0x000220a9,0xffffffff},
	{0x000220aa,0xffffffff},
	{0x000220ac,0xffffffff},
	{0x000220ad,0xffffffff},
	{0x000220ae,0xffffffff},
	{0x000220c0,0xffffffff},
	{0x000220c1,0xffffffff},
	{0x000220c2,0xffffffff},
	{0x000220c4,0xffffffff},
	{0x000220c5,0xffffffff},
	{0x000220c6,0xffffffff},
	{0x000220c8,0xffffffff},
	{0x000220c9,0xffffffff},
	{0x000220ca,0xffffffff},
	{0x000220cc,0xffffffff},
	{0x000220cd,0xffffffff},
	{0x000220ce,0xffffffff},
	{0x000220d0,0xffffffff},
	{0x000220d1,0xffffffff},
	{0x000220d2,0xffffffff},
	{0x000220d4,0xffffffff},
	{0x000220d5,0xffffffff},
	{0x000220d6,0xffffffff},
	{0x000220d8,0xffffffff},
	{0x000220d9,0xffffffff},
	{0x000220da,0xffffffff},
	{0x000220dc,0xffffffff},
	{0x000220dd,0xffffffff},
	{0x000220de,0xffffffff},
	{0x000220e0,0xffffffff},
	{0x000220e1,0xffffffff},
	{0x000220e2,0xffffffff},
	{0x000220e4,0xffffffff},
	{0x000220e5,0xffffffff},
	{0x000220e6,0xffffffff},
	{0x000220e8,0xffffffff},
	{0x000220e9,0xffffffff},
	{0x000220ea,0xffffffff},
	{0x000220ec,0xffffffff},
	{0x000220ed,0xffffffff},
	{0x000220ee,0xffffffff},
};

int main(int argc, char **argv)
{
	const char *bdf = "0000:02:00.0";
	char p[256]; int fd, i, dry = 0, list = 0;
	volatile uint32_t *M = NULL;

	for (i = 1; i < argc; i++) {
		if (!strcmp(argv[i], "-n")) dry = 1;
		else if (!strcmp(argv[i], "-a")) list = 1;
		else bdf = argv[i];
	}
	if (list) {
		for (i = 0; i < (int)(sizeof R / sizeof R[0]); i++)
			printf("%08x\n", R[i][0]);
		return 0;
	}
	if (!dry) {
		snprintf(p, sizeof p, "/sys/bus/pci/devices/%s/resource0", bdf);
		fd = open(p, O_RDWR | O_SYNC);
		if (fd < 0) { perror("open"); return 1; }
		M = mmap(NULL, 32u*1024*1024, PROT_READ|PROT_WRITE, MAP_SHARED, fd, 0);
		if (M == MAP_FAILED) { perror("mmap"); return 1; }
	}
	for (i = 0; i < (int)(sizeof R / sizeof R[0]); i++) {
		if (dry) printf("%08x %08x\n", R[i][0], R[i][1]);
		else { M[R[i][0]] = R[i][1]; __sync_synchronize(); }
	}
	if (!dry)
		printf("fm6000_cmminit: %d writes\n",
		       (int)(sizeof R / sizeof R[0]));
	return 0;
}
