/* fm6000_safmatrix.c - SAF_MATRIX, the store-and-forward port matrix.
 *
 * GENERATED by asic/fm6000/tools/gen_safmatrix.py --c. Edit the generator.
 *
 * 76 entries x 3 words at 0x0a0000 (pitch 4). The 96 bits are a PORT BITMAP:
 * entry p is the set of ports p may store-and-forward with.
 *
 * This is 74% of everything the vendor replay still supplied -- 34,668 writes
 * over 168 addresses -- because it TRACKS LINK STATE and is rewritten as ports
 * come up. Its converged state is only four distinct values:
 *
 *   ports 0, 2        all bits
 *   port 1            bits 0..81
 *   ports 3, 20, 40   {0,1,2}                  the cages with a transceiver
 *   other 50 front    {0,1,2,3} | {20,40}      CPU/mgmt ports + the linked ports
 *
 * ⚠ CONFIG-DEPENDENT. Ports 20 and 40 are et2 and et1. Change which cages have a
 * link and this matrix changes -- regenerate rather than assuming.
 *
 * usage: fm6000_safmatrix [-n | -a] [-b bdf]
 * SPDX-License-Identifier: GPL-2.0-or-later */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdint.h>
#include <sys/mman.h>

static const struct { uint32_t addr, val; } W[] = {
	{ 0x0a0000, 0xffffffff },
	{ 0x0a0001, 0xffffffff },
	{ 0x0a0002, 0xffffffff },
	{ 0x0a0004, 0xffffffff },
	{ 0x0a0005, 0xffffffff },
	{ 0x0a0006, 0x0003ffff },
	{ 0x0a0008, 0xffffffff },
	{ 0x0a0009, 0xffffffff },
	{ 0x0a000a, 0xffffffff },
	{ 0x0a000c, 0x00000007 },
	{ 0x0a000d, 0x00000000 },
	{ 0x0a000e, 0x00000000 },
	{ 0x0a0050, 0x00000007 },
	{ 0x0a0051, 0x00000000 },
	{ 0x0a0052, 0x00000000 },
	{ 0x0a0054, 0x0010000f },
	{ 0x0a0055, 0x00000100 },
	{ 0x0a0056, 0x00000000 },
	{ 0x0a0058, 0x0010000f },
	{ 0x0a0059, 0x00000100 },
	{ 0x0a005a, 0x00000000 },
	{ 0x0a005c, 0x0010000f },
	{ 0x0a005d, 0x00000100 },
	{ 0x0a005e, 0x00000000 },
	{ 0x0a0060, 0x0010000f },
	{ 0x0a0061, 0x00000100 },
	{ 0x0a0062, 0x00000000 },
	{ 0x0a0064, 0x0010000f },
	{ 0x0a0065, 0x00000100 },
	{ 0x0a0066, 0x00000000 },
	{ 0x0a0068, 0x0010000f },
	{ 0x0a0069, 0x00000100 },
	{ 0x0a006a, 0x00000000 },
	{ 0x0a006c, 0x0010000f },
	{ 0x0a006d, 0x00000100 },
	{ 0x0a006e, 0x00000000 },
	{ 0x0a0070, 0x0010000f },
	{ 0x0a0071, 0x00000100 },
	{ 0x0a0072, 0x00000000 },
	{ 0x0a0074, 0x0010000f },
	{ 0x0a0075, 0x00000100 },
	{ 0x0a0076, 0x00000000 },
	{ 0x0a0078, 0x0010000f },
	{ 0x0a0079, 0x00000100 },
	{ 0x0a007a, 0x00000000 },
	{ 0x0a007c, 0x0010000f },
	{ 0x0a007d, 0x00000100 },
	{ 0x0a007e, 0x00000000 },
	{ 0x0a0080, 0x0010000f },
	{ 0x0a0081, 0x00000100 },
	{ 0x0a0082, 0x00000000 },
	{ 0x0a0084, 0x0010000f },
	{ 0x0a0085, 0x00000100 },
	{ 0x0a0086, 0x00000000 },
	{ 0x0a0088, 0x0010000f },
	{ 0x0a0089, 0x00000100 },
	{ 0x0a008a, 0x00000000 },
	{ 0x0a008c, 0x0010000f },
	{ 0x0a008d, 0x00000100 },
	{ 0x0a008e, 0x00000000 },
	{ 0x0a0090, 0x0010000f },
	{ 0x0a0091, 0x00000100 },
	{ 0x0a0092, 0x00000000 },
	{ 0x0a0094, 0x0010000f },
	{ 0x0a0095, 0x00000100 },
	{ 0x0a0096, 0x00000000 },
	{ 0x0a0098, 0x0010000f },
	{ 0x0a0099, 0x00000100 },
	{ 0x0a009a, 0x00000000 },
	{ 0x0a009c, 0x0010000f },
	{ 0x0a009d, 0x00000100 },
	{ 0x0a009e, 0x00000000 },
	{ 0x0a00a0, 0x00000007 },
	{ 0x0a00a1, 0x00000000 },
	{ 0x0a00a2, 0x00000000 },
	{ 0x0a00a4, 0x0010000f },
	{ 0x0a00a5, 0x00000100 },
	{ 0x0a00a6, 0x00000000 },
	{ 0x0a00a8, 0x0010000f },
	{ 0x0a00a9, 0x00000100 },
	{ 0x0a00aa, 0x00000000 },
	{ 0x0a00ac, 0x0010000f },
	{ 0x0a00ad, 0x00000100 },
	{ 0x0a00ae, 0x00000000 },
	{ 0x0a00b0, 0x0010000f },
	{ 0x0a00b1, 0x00000100 },
	{ 0x0a00b2, 0x00000000 },
	{ 0x0a00b4, 0x0010000f },
	{ 0x0a00b5, 0x00000100 },
	{ 0x0a00b6, 0x00000000 },
	{ 0x0a00b8, 0x0010000f },
	{ 0x0a00b9, 0x00000100 },
	{ 0x0a00ba, 0x00000000 },
	{ 0x0a00bc, 0x0010000f },
	{ 0x0a00bd, 0x00000100 },
	{ 0x0a00be, 0x00000000 },
	{ 0x0a00d0, 0x0010000f },
	{ 0x0a00d1, 0x00000100 },
	{ 0x0a00d2, 0x00000000 },
	{ 0x0a00d4, 0x0010000f },
	{ 0x0a00d5, 0x00000100 },
	{ 0x0a00d6, 0x00000000 },
	{ 0x0a00d8, 0x0010000f },
	{ 0x0a00d9, 0x00000100 },
	{ 0x0a00da, 0x00000000 },
	{ 0x0a00dc, 0x0010000f },
	{ 0x0a00dd, 0x00000100 },
	{ 0x0a00de, 0x00000000 },
	{ 0x0a00e0, 0x0010000f },
	{ 0x0a00e1, 0x00000100 },
	{ 0x0a00e2, 0x00000000 },
	{ 0x0a00e4, 0x0010000f },
	{ 0x0a00e5, 0x00000100 },
	{ 0x0a00e6, 0x00000000 },
	{ 0x0a00e8, 0x0010000f },
	{ 0x0a00e9, 0x00000100 },
	{ 0x0a00ea, 0x00000000 },
	{ 0x0a00ec, 0x0010000f },
	{ 0x0a00ed, 0x00000100 },
	{ 0x0a00ee, 0x00000000 },
	{ 0x0a00f0, 0x0010000f },
	{ 0x0a00f1, 0x00000100 },
	{ 0x0a00f2, 0x00000000 },
	{ 0x0a00f4, 0x0010000f },
	{ 0x0a00f5, 0x00000100 },
	{ 0x0a00f6, 0x00000000 },
	{ 0x0a00f8, 0x0010000f },
	{ 0x0a00f9, 0x00000100 },
	{ 0x0a00fa, 0x00000000 },
	{ 0x0a00fc, 0x0010000f },
	{ 0x0a00fd, 0x00000100 },
	{ 0x0a00fe, 0x00000000 },
	{ 0x0a0100, 0x0010000f },
	{ 0x0a0101, 0x00000100 },
	{ 0x0a0102, 0x00000000 },
	{ 0x0a0104, 0x0010000f },
	{ 0x0a0105, 0x00000100 },
	{ 0x0a0106, 0x00000000 },
	{ 0x0a0108, 0x0010000f },
	{ 0x0a0109, 0x00000100 },
	{ 0x0a010a, 0x00000000 },
	{ 0x0a010c, 0x0010000f },
	{ 0x0a010d, 0x00000100 },
	{ 0x0a010e, 0x00000000 },
	{ 0x0a0110, 0x0010000f },
	{ 0x0a0111, 0x00000100 },
	{ 0x0a0112, 0x00000000 },
	{ 0x0a0114, 0x0010000f },
	{ 0x0a0115, 0x00000100 },
	{ 0x0a0116, 0x00000000 },
	{ 0x0a0118, 0x0010000f },
	{ 0x0a0119, 0x00000100 },
	{ 0x0a011a, 0x00000000 },
	{ 0x0a011c, 0x0010000f },
	{ 0x0a011d, 0x00000100 },
	{ 0x0a011e, 0x00000000 },
	{ 0x0a0120, 0x0010000f },
	{ 0x0a0121, 0x00000100 },
	{ 0x0a0122, 0x00000000 },
	{ 0x0a0124, 0x0010000f },
	{ 0x0a0125, 0x00000100 },
	{ 0x0a0126, 0x00000000 },
	{ 0x0a0128, 0x0010000f },
	{ 0x0a0129, 0x00000100 },
	{ 0x0a012a, 0x00000000 },
	{ 0x0a012c, 0x0010000f },
	{ 0x0a012d, 0x00000100 },
	{ 0x0a012e, 0x00000000 },
};

static volatile uint32_t *M;

int main(int argc, char **argv)
{
	const char *bdf = "0000:02:00.0";
	int dry = 0, list = 0, i;

	for (i = 1; i < argc; i++) {
		if      (!strcmp(argv[i], "-n")) dry = 1;
		else if (!strcmp(argv[i], "-a")) list = 1;
		else if (!strcmp(argv[i], "-b") && i + 1 < argc) bdf = argv[++i];
		else { fprintf(stderr, "usage: %s [-n|-a] [-b bdf]\n", argv[0]); return 2; }
	}

	if (!dry && !list) {
		char path[256];
		snprintf(path, sizeof path, "/sys/bus/pci/devices/%s/resource0", bdf);
		int fd = open(path, O_RDWR | O_SYNC);
		if (fd < 0) { perror("open resource0"); return 1; }
		M = mmap(NULL, 32u * 1024 * 1024, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
		if (M == MAP_FAILED) { perror("mmap"); return 1; }
	}

	for (i = 0; i < (int)(sizeof W / sizeof W[0]); i++) {
		if (list)      printf("%08x\n", W[i].addr);
		else if (dry)  printf("%08x %08x\n", W[i].addr, W[i].val);
		else         { M[W[i].addr] = W[i].val; __sync_synchronize(); }
	}
	if (!dry && !list)
		fprintf(stderr, "fm6000_safmatrix: %d writes\n",
		        (int)(sizeof W / sizeof W[0]));
	return 0;
}
