/* fm6000_esched.c - egress scheduler per-port config.
 *
 * GENERATED by asic/fm6000/tools/gen_esched.py --c. Edit the generator.
 *
 * The 104 write-once ESCHED addresses fm6000_eschedinit leaves uncovered. The
 * whole block is one rule:
 *
 *     for each of the 52 front-panel data ports (20-47, 52-75):
 *         ESCHED_CFG_1[port] = 0xffffff
 *         ESCHED_CFG_2[port] = 0xffffff
 *
 * The port set is the configured-port set MINUS {0, 1, 3} -- the CPU and
 * management ports, which an egress scheduler does not schedule like a data
 * port. 0xffffff is 24 bits all set: the credit field at maximum, every
 * front-panel port unshaped and equal.
 *
 * ⚠ Port 0 is NOT ours. The replay writes it 37/61 times with 0xfff800/0xfff000
 * -- a different, shaped value -- and it stays in the replay.
 *
 * Verified byte-identical against the executed image: 104 of 104, and the
 * derived port set checked in both directions.
 *
 * usage: fm6000_esched [-n | -a] [-b bdf]
 * SPDX-License-Identifier: GPL-2.0-or-later */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdint.h>
#include <sys/mman.h>

#define ESCHED_CFG_1 0x002000u
#define ESCHED_CFG_2 0x002080u
#define ESCHED_CFG_VALUE 0x00ffffffu

/* the 52 front-panel data ports */
static const unsigned char front_panel[] = {
	20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
	44, 45, 46, 47, 52, 53, 54, 55, 56, 57, 58, 59,
	60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75,
};

static volatile uint32_t *M;

int main(int argc, char **argv)
{
	const char *bdf = "0000:02:00.0";
	int dry = 0, list = 0, i, k, n = 0;
	static const uint32_t base[2] = { ESCHED_CFG_1, ESCHED_CFG_2 };

	for (i = 1; i < argc; i++) {
		if      (!strcmp(argv[i], "-n")) dry = 1;
		else if (!strcmp(argv[i], "-a")) list = 1;
		else if (!strcmp(argv[i], "-b") && i + 1 < argc) bdf = argv[++i];
		else { fprintf(stderr, "usage: %s [-n|-a] [-b bdf]\n", argv[0]); return 2; }
	}

	if (!dry && !list) {
		char path[256];
		snprintf(path, sizeof path, "/sys/bus/pci/devices/%s/resource0", bdf);
		int fd = open(path, O_RDWR | O_SYNC);
		if (fd < 0) { perror("open resource0"); return 1; }
		M = mmap(NULL, 32u * 1024 * 1024, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
		if (M == MAP_FAILED) { perror("mmap"); return 1; }
	}

	for (k = 0; k < 2; k++) {
		for (i = 0; i < (int)sizeof front_panel; i++) {
			uint32_t a = base[k] + front_panel[i];
			if (list)      printf("%08x\n", a);
			else if (dry)  printf("%08x %08x\n", a, ESCHED_CFG_VALUE);
			else         { M[a] = ESCHED_CFG_VALUE; __sync_synchronize(); }
			n++;
		}
	}
	if (!dry && !list)
		fprintf(stderr, "fm6000_esched: %d writes\n", n);
	return 0;
}
