/* fm6000_cmwm.c - congestion-management watermark tables.
 *
 * GENERATED by asic/fm6000/tools/gen_cmwm.py --c. Edit the generator.
 *
 * Six per-port tables, one word per entry, indexed port * 16 + traffic_class:
 *
 *     RXMP_PRIVATE    0x112800   76 ports x 12 classes
 *     RXMP_HOG        0x113000   76 x 16   (a single constant, 0xffffffff)
 *     TXMP_PRIVATE    0x113800   80 x 16
 *     TXMP_HOG        0x114000   80 x 16
 *     RXMP_PAUSE_ON   0x115000   76 x 12
 *     RXMP_PAUSE_OFF  0x115800   76 x 12
 *
 * Emitted structurally -- port groups and per-class vectors -- rather than as
 * 6,512 opaque words, because the structure is the point: ports 1-2, 4-19 and
 * 48-51 take "no limit" in the RX tables while 0, 3, 20-47 and 52-75 take real
 * watermarks, and TX ports 76-79 are zeroed.
 *
 * WARNING: these decide when the chip drops and when it asserts PAUSE. A wrong
 * value does not fail loudly -- it appears as loss or head-of-line blocking
 * under load, which a transit test will not catch. The generator byte-verifies
 * against the image in both directions.
 *
 * usage: fm6000_cmwm [-n | -a] [-b bdf]
 * SPDX-License-Identifier: GPL-2.0-or-later */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdint.h>
#include <sys/mman.h>

struct group { int lo, hi; const uint32_t *vals; };
struct table { const char *name; uint32_t base; int nports, nclass;
               const struct group *groups; int ngroups; };

static const uint32_t V_RXMP_PRIVATE_0[] = { 0x13003au, 0x60014u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u };
static const uint32_t V_RXMP_PRIVATE_1[] = { 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu };
static const struct group G_RXMP_PRIVATE[] = {
	{ 0, 0, V_RXMP_PRIVATE_0 },
	{ 3, 3, V_RXMP_PRIVATE_0 },
	{ 20, 47, V_RXMP_PRIVATE_0 },
	{ 52, 75, V_RXMP_PRIVATE_0 },
	{ 1, 2, V_RXMP_PRIVATE_1 },
	{ 4, 19, V_RXMP_PRIVATE_1 },
	{ 48, 51, V_RXMP_PRIVATE_1 },
};

static const uint32_t V_RXMP_HOG_0[] = { 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu };
static const struct group G_RXMP_HOG[] = {
	{ 0, 75, V_RXMP_HOG_0 },
};

static const uint32_t V_TXMP_PRIVATE_0[] = { 0x8014u, 0x8014u, 0x8014u, 0x8014u, 0x8014u, 0x8014u, 0x8014u, 0x8014u, 0x8014u, 0x8014u, 0x8014u, 0x8000u, 0x8000u, 0x8000u, 0x8000u, 0x7u };
static const uint32_t V_TXMP_PRIVATE_1[] = { 0x3fffu, 0x3fffu, 0x3fffu, 0x3fffu, 0x3fffu, 0x3fffu, 0x3fffu, 0x3fffu, 0x3fffu, 0x3fffu, 0x3fffu, 0x3fffu, 0x3fffu, 0x3fffu, 0x3fffu, 0x3fffu };
static const uint32_t V_TXMP_PRIVATE_2[] = { 0x8004u, 0x8004u, 0x8004u, 0x8004u, 0x8004u, 0x8004u, 0x8004u, 0x8004u, 0x8004u, 0x8000u, 0x8000u, 0x8000u, 0x8000u, 0x8000u, 0x8000u, 0x7u };
static const uint32_t V_TXMP_PRIVATE_3[] = { 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u };
static const struct group G_TXMP_PRIVATE[] = {
	{ 0, 0, V_TXMP_PRIVATE_0 },
	{ 1, 2, V_TXMP_PRIVATE_1 },
	{ 4, 19, V_TXMP_PRIVATE_1 },
	{ 48, 51, V_TXMP_PRIVATE_1 },
	{ 3, 3, V_TXMP_PRIVATE_2 },
	{ 20, 47, V_TXMP_PRIVATE_2 },
	{ 52, 75, V_TXMP_PRIVATE_2 },
	{ 76, 79, V_TXMP_PRIVATE_3 },
};

static const uint32_t V_TXMP_HOG_0[] = { 0xd6u, 0xd6u, 0xd6u, 0xd6u, 0xd6u, 0xd6u, 0xd6u, 0xd6u, 0xd6u, 0xd6u, 0xd6u, 0x0u, 0x0u, 0x0u, 0x0u, 0xcdu };
static const uint32_t V_TXMP_HOG_1[] = { 0x3fffu, 0x3fffu, 0x3fffu, 0x3fffu, 0x3fffu, 0x3fffu, 0x3fffu, 0x3fffu, 0x3fffu, 0x3fffu, 0x3fffu, 0x3fffu, 0x3fffu, 0x3fffu, 0x3fffu, 0x3fffu };
static const uint32_t V_TXMP_HOG_2[] = { 0x15f5u, 0x15f5u, 0x15f5u, 0x15f5u, 0x15f5u, 0x15f5u, 0x15f5u, 0x15f5u, 0x15f5u, 0x15f5u, 0x15f5u, 0x0u, 0x0u, 0x0u, 0x0u, 0xcdu };
static const uint32_t V_TXMP_HOG_3[] = { 0x111u, 0x111u, 0x111u, 0x111u, 0x111u, 0x111u, 0x111u, 0x111u, 0x111u, 0x111u, 0x111u, 0x111u, 0x111u, 0x111u, 0x111u, 0x111u };
static const struct group G_TXMP_HOG[] = {
	{ 0, 0, V_TXMP_HOG_0 },
	{ 1, 2, V_TXMP_HOG_1 },
	{ 4, 19, V_TXMP_HOG_1 },
	{ 48, 51, V_TXMP_HOG_1 },
	{ 3, 3, V_TXMP_HOG_2 },
	{ 20, 47, V_TXMP_HOG_2 },
	{ 52, 75, V_TXMP_HOG_2 },
	{ 76, 79, V_TXMP_HOG_3 },
};

static const uint32_t V_RXMP_PAUSE_ON_0[] = { 0x4000c000u, 0x4000c000u, 0x4000c000u, 0x4000c000u, 0x4000c000u, 0x4000c000u, 0x4000c000u, 0x4000c000u, 0x4000c000u, 0x4000c000u, 0x4000c000u, 0x4000c000u };
static const uint32_t V_RXMP_PAUSE_ON_1[] = { 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu };
static const struct group G_RXMP_PAUSE_ON[] = {
	{ 0, 0, V_RXMP_PAUSE_ON_0 },
	{ 20, 47, V_RXMP_PAUSE_ON_0 },
	{ 52, 75, V_RXMP_PAUSE_ON_0 },
	{ 1, 19, V_RXMP_PAUSE_ON_1 },
	{ 48, 51, V_RXMP_PAUSE_ON_1 },
};

static const uint32_t V_RXMP_PAUSE_OFF_0[] = { 0x4000c000u, 0x4000c000u, 0x4000c000u, 0x4000c000u, 0x4000c000u, 0x4000c000u, 0x4000c000u, 0x4000c000u, 0x4000c000u, 0x4000c000u, 0x4000c000u, 0x4000c000u };
static const uint32_t V_RXMP_PAUSE_OFF_1[] = { 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu };
static const struct group G_RXMP_PAUSE_OFF[] = {
	{ 0, 0, V_RXMP_PAUSE_OFF_0 },
	{ 20, 47, V_RXMP_PAUSE_OFF_0 },
	{ 52, 75, V_RXMP_PAUSE_OFF_0 },
	{ 1, 19, V_RXMP_PAUSE_OFF_1 },
	{ 48, 51, V_RXMP_PAUSE_OFF_1 },
};

static const struct table T[] = {
	{ "RXMP_PRIVATE", 0x112800u, 76, 12, G_RXMP_PRIVATE, 7 },
	{ "RXMP_HOG", 0x113000u, 76, 16, G_RXMP_HOG, 1 },
	{ "TXMP_PRIVATE", 0x113800u, 80, 16, G_TXMP_PRIVATE, 8 },
	{ "TXMP_HOG", 0x114000u, 80, 16, G_TXMP_HOG, 8 },
	{ "RXMP_PAUSE_ON", 0x115000u, 76, 12, G_RXMP_PAUSE_ON, 5 },
	{ "RXMP_PAUSE_OFF", 0x115800u, 76, 12, G_RXMP_PAUSE_OFF, 5 },
};

static volatile uint32_t *M;

int main(int argc, char **argv)
{
	const char *bdf = "0000:02:00.0";
	int dry = 0, list = 0, i, g, p, c;
	long n = 0;

	for (i = 1; i < argc; i++) {
		if      (!strcmp(argv[i], "-n")) dry = 1;
		else if (!strcmp(argv[i], "-a")) list = 1;
		else if (!strcmp(argv[i], "-b") && i + 1 < argc) bdf = argv[++i];
		else { fprintf(stderr, "usage: %s [-n|-a] [-b bdf]\n", argv[0]); return 2; }
	}

	if (!dry && !list) {
		char path[256];
		snprintf(path, sizeof path, "/sys/bus/pci/devices/%s/resource0", bdf);
		int fd = open(path, O_RDWR | O_SYNC);
		if (fd < 0) { perror("open resource0"); return 1; }
		M = mmap(NULL, 32u * 1024 * 1024, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
		if (M == MAP_FAILED) { perror("mmap"); return 1; }
	}

	for (i = 0; i < (int)(sizeof T / sizeof T[0]); i++)
		for (g = 0; g < T[i].ngroups; g++)
			for (p = T[i].groups[g].lo; p <= T[i].groups[g].hi; p++) {
				if (p >= T[i].nports) continue;
				for (c = 0; c < T[i].nclass; c++) {
					uint32_t a = T[i].base + p * 16 + c;
					uint32_t v = T[i].groups[g].vals[c];
					if (list)      printf("%08x\n", a);
					else if (dry)  printf("%08x %08x\n", a, v);
					else         { M[a] = v; __sync_synchronize(); }
					n++;
				}
			}
	if (!dry && !list)
		fprintf(stderr, "fm6000_cmwm: %ld writes\n", n);
	return 0;
}
