/* fm6000_sbusseq.c - SerDes SBus bring-up sequence.
 * GENERATED by asic/fm6000/tools/gen_sbusseq.py -- do not edit by hand.
 *
 * 1243 transactions on three registers, expressed as 16 program steps.
 * Each step is {payload, command, repeat}: write SBUS_REQUEST when the
 * payload is non-zero, then SBUS_COMMAND 0, then the command word
 * 01.DD.RR.VV (device, register, value).
 *
 * ⚠ The structure is recovered exactly; the register SEMANTICS are not.
 * See gen_sbusseq.py for what that means.
 * SPDX-License-Identifier: GPL-2.0-or-later
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdint.h>
#include <sys/mman.h>

#define SBUS_CFG      0x00f000u
#define SBUS_COMMAND  0x00f001u
#define SBUS_REQUEST  0x00f002u

static volatile uint32_t *M;

/* distinct steps: {kind, a, b};  kind 0 = raw write a=b,
 * kind 1 = transaction with payload a and command b */
static const uint32_t T[][3] = {
	{ 0, 0x0000f000u, 0x00000000u },
	{ 1, 0x00000004u, 0x0121fe0au },
	{ 1, 0x00000000u, 0x01220100u },
	{ 1, 0x00000000u, 0x0122010fu },
	{ 1, 0x00000000u, 0x01220200u },
	{ 1, 0x00000000u, 0x0122020fu },
	{ 1, 0x00000000u, 0x01220300u },
	{ 1, 0x00000000u, 0x0122030fu },
	{ 1, 0x00000000u, 0x01220400u },
	{ 1, 0x00000000u, 0x0122040fu },
	{ 1, 0x00000000u, 0x01220100u },
	{ 1, 0x00000000u, 0x0122010fu },
	{ 1, 0x00000000u, 0x01220200u },
	{ 1, 0x00000000u, 0x0122020fu },
	{ 1, 0x00000000u, 0x01220300u },
	{ 1, 0x00000000u, 0x0122030fu },
	{ 1, 0x00000000u, 0x01220400u },
	{ 1, 0x00000000u, 0x0122040fu },
	{ 1, 0x00000000u, 0x01220100u },
	{ 1, 0x00000000u, 0x0122010fu },
	{ 1, 0x00000000u, 0x01220200u },
	{ 1, 0x00000000u, 0x0122020fu },
	{ 1, 0x00000000u, 0x01220300u },
	{ 1, 0x00000000u, 0x0122030fu },
	{ 1, 0x00000000u, 0x01220400u },
	{ 1, 0x00000000u, 0x0122040fu },
	{ 1, 0x00000000u, 0x01220100u },
	{ 1, 0x00000000u, 0x0122010fu },
	{ 1, 0x00000000u, 0x01220200u },
	{ 1, 0x00000000u, 0x0122020fu },
	{ 1, 0x00000000u, 0x01220300u },
	{ 1, 0x00000000u, 0x0122030fu },
	{ 1, 0x00000000u, 0x01220400u },
	{ 1, 0x00000000u, 0x0122040fu },
	{ 1, 0x00000000u, 0x01220100u },
	{ 1, 0x00000000u, 0x0122010fu },
	{ 1, 0x00000000u, 0x01220200u },
	{ 1, 0x00000000u, 0x0122020fu },
	{ 1, 0x00000000u, 0x01220300u },
	{ 1, 0x00000000u, 0x0122030fu },
	{ 1, 0x00000000u, 0x01220400u },
	{ 1, 0x00000000u, 0x0122040fu },
	{ 1, 0x00000000u, 0x01220100u },
	{ 1, 0x00000000u, 0x0122010fu },
	{ 1, 0x00000000u, 0x01220200u },
	{ 1, 0x00000000u, 0x0122020fu },
	{ 1, 0x00000000u, 0x01220300u },
	{ 1, 0x00000000u, 0x0122030fu },
	{ 1, 0x00000000u, 0x01220400u },
	{ 1, 0x00000000u, 0x0122040fu },
	{ 1, 0x00000000u, 0x01220100u },
	{ 1, 0x00000000u, 0x0122010fu },
	{ 1, 0x00000000u, 0x01220200u },
	{ 1, 0x00000000u, 0x0122020fu },
	{ 1, 0x00000000u, 0x01220300u },
	{ 1, 0x00000000u, 0x0122030fu },
	{ 1, 0x00000000u, 0x01220400u },
	{ 1, 0x00000000u, 0x0122040fu },
	{ 1, 0x00000000u, 0x01220100u },
	{ 1, 0x00000000u, 0x0122010fu },
	{ 1, 0x00000000u, 0x01220200u },
	{ 1, 0x00000000u, 0x0122020fu },
	{ 1, 0x00000000u, 0x01220300u },
	{ 1, 0x00000000u, 0x0122030fu },
	{ 1, 0x00000000u, 0x01220400u },
	{ 1, 0x00000000u, 0x0122040fu },
	{ 1, 0x00000000u, 0x01220100u },
	{ 1, 0x00000000u, 0x0122010fu },
	{ 1, 0x00000000u, 0x01220200u },
	{ 1, 0x00000000u, 0x0122020fu },
	{ 1, 0x00000000u, 0x01220300u },
	{ 1, 0x00000000u, 0x0122030fu },
	{ 1, 0x00000000u, 0x01220400u },
	{ 1, 0x00000000u, 0x0122040fu },
	{ 0, 0x0000f000u, 0x00000000u },
	{ 0, 0x0000f004u, 0x00000000u },
	{ 1, 0x00000003u, 0x0121fd0cu },
	{ 1, 0x00000001u, 0x0121fd0cu },
	{ 1, 0x00000008u, 0x0121fd0cu },
	{ 0, 0x0000f004u, 0x00000002u },
	{ 1, 0x00000000u, 0x0121fd01u },
	{ 1, 0x00000002u, 0x0121fd02u },
	{ 1, 0x00000000u, 0x0121fd03u },
	{ 1, 0x00000018u, 0x0121fd0cu },
	{ 1, 0x00000008u, 0x0121fd0cu },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd00u },
	{ 1, 0x00000000u, 0x0122fd02u },
	{ 1, 0x00000000u, 0x0121fd01u },
	{ 1, 0x00000004u, 0x0121fd02u },
	{ 1, 0x00000000u, 0x0121fd03u },
	{ 1, 0x00000018u, 0x0121fd0cu },
	{ 1, 0x00000008u, 0x0121fd0cu },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd00u },
	{ 1, 0x00000000u, 0x0122fd02u },
	{ 1, 0x00000000u, 0x0121fd0cu },
	{ 1, 0x0000001fu, 0x01214501u },
	{ 1, 0x0000003fu, 0x01214502u },
	{ 1, 0x0000001fu, 0x01214901u },
	{ 1, 0x0000003fu, 0x01214902u },
	{ 1, 0x00000000u, 0x01204900u },
	{ 1, 0x00000010u, 0x01214917u },
	{ 1, 0x00000000u, 0x01214906u },
	{ 1, 0x00000000u, 0x0122491fu },
	{ 1, 0x00000000u, 0x01224924u },
	{ 1, 0x00000000u, 0x01224920u },
	{ 1, 0x00000000u, 0x01224921u },
	{ 1, 0x00000000u, 0x01224922u },
	{ 1, 0x00000000u, 0x01224923u },
	{ 1, 0x00000000u, 0x01224924u },
	{ 1, 0x00000000u, 0x01214917u },
	{ 1, 0x0000000eu, 0x0121492au },
	{ 1, 0x00000002u, 0x0121492bu },
	{ 1, 0x00000000u, 0x01204500u },
	{ 1, 0x00000010u, 0x01214517u },
	{ 1, 0x00000000u, 0x01214506u },
	{ 1, 0x00000000u, 0x0122451fu },
	{ 1, 0x00000000u, 0x01224524u },
	{ 1, 0x00000000u, 0x01224520u },
	{ 1, 0x00000000u, 0x01224521u },
	{ 1, 0x00000000u, 0x01224522u },
	{ 1, 0x00000000u, 0x01224523u },
	{ 1, 0x00000000u, 0x01224524u },
	{ 1, 0x00000000u, 0x01214517u },
	{ 1, 0x0000000eu, 0x0121452au },
	{ 1, 0x00000002u, 0x0121452bu },
	{ 1, 0x00000000u, 0x0122491fu },
	{ 1, 0x00000000u, 0x01224924u },
	{ 1, 0x00000000u, 0x01224925u },
	{ 1, 0x00000000u, 0x01224926u },
	{ 1, 0x00000000u, 0x01224927u },
	{ 1, 0x00000000u, 0x0121fd01u },
	{ 1, 0x00000020u, 0x0121fd02u },
	{ 1, 0x00000049u, 0x0121fd03u },
	{ 1, 0x00000018u, 0x0121fd0cu },
	{ 1, 0x00000008u, 0x0121fd0cu },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd00u },
	{ 1, 0x00000000u, 0x0122fd02u },
	{ 1, 0x00000000u, 0x0122451fu },
	{ 1, 0x00000000u, 0x0122491fu },
	{ 1, 0x00000000u, 0x0121fd01u },
	{ 1, 0x00000020u, 0x0121fd02u },
	{ 1, 0x00000049u, 0x0121fd03u },
	{ 1, 0x00000018u, 0x0121fd0cu },
	{ 1, 0x00000008u, 0x0121fd0cu },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd00u },
	{ 1, 0x00000000u, 0x0122fd02u },
	{ 1, 0x00000000u, 0x0122451fu },
	{ 1, 0x00000000u, 0x01224524u },
	{ 1, 0x00000000u, 0x01224525u },
	{ 1, 0x00000000u, 0x01224526u },
	{ 1, 0x00000000u, 0x01224527u },
	{ 1, 0x00000000u, 0x0121fd01u },
	{ 1, 0x00000020u, 0x0121fd02u },
	{ 1, 0x00000045u, 0x0121fd03u },
	{ 1, 0x00000018u, 0x0121fd0cu },
	{ 1, 0x00000008u, 0x0121fd0cu },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd00u },
	{ 1, 0x00000000u, 0x0122fd02u },
	{ 1, 0x00000000u, 0x0122451fu },
	{ 1, 0x00000000u, 0x0121fd01u },
	{ 1, 0x00000020u, 0x0121fd02u },
	{ 1, 0x00000045u, 0x0121fd03u },
	{ 1, 0x00000018u, 0x0121fd0cu },
	{ 1, 0x00000008u, 0x0121fd0cu },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd00u },
	{ 1, 0x00000000u, 0x0122fd02u },
	{ 1, 0x00000000u, 0x0121fd01u },
	{ 1, 0x00000020u, 0x0121fd02u },
	{ 1, 0x00000049u, 0x0121fd03u },
	{ 1, 0x00000018u, 0x0121fd0cu },
	{ 1, 0x00000008u, 0x0121fd0cu },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd00u },
	{ 1, 0x00000000u, 0x0122fd02u },
	{ 1, 0x00000016u, 0x0121492au },
	{ 1, 0x00000000u, 0x0121fd01u },
	{ 1, 0x00000020u, 0x0121fd02u },
	{ 1, 0x00000045u, 0x0121fd03u },
	{ 1, 0x00000018u, 0x0121fd0cu },
	{ 1, 0x00000008u, 0x0121fd0cu },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd00u },
	{ 1, 0x00000000u, 0x0122fd02u },
	{ 1, 0x00000016u, 0x0121452au },
	{ 1, 0x00000000u, 0x0121fd01u },
	{ 1, 0x00000020u, 0x0121fd02u },
	{ 1, 0x00000049u, 0x0121fd03u },
	{ 1, 0x00000018u, 0x0121fd0cu },
	{ 1, 0x00000008u, 0x0121fd0cu },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd00u },
	{ 1, 0x00000000u, 0x0122fd02u },
	{ 1, 0x0000000eu, 0x0121492au },
	{ 1, 0x00000000u, 0x0121fd01u },
	{ 1, 0x00000020u, 0x0121fd02u },
	{ 1, 0x00000045u, 0x0121fd03u },
	{ 1, 0x00000018u, 0x0121fd0cu },
	{ 1, 0x00000008u, 0x0121fd0cu },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd00u },
	{ 1, 0x00000000u, 0x0122fd02u },
	{ 1, 0x0000000eu, 0x0121452au },
	{ 1, 0x00000000u, 0x0121fd01u },
	{ 1, 0x00000020u, 0x0121fd02u },
	{ 1, 0x00000049u, 0x0121fd03u },
	{ 1, 0x00000018u, 0x0121fd0cu },
	{ 1, 0x00000008u, 0x0121fd0cu },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd00u },
	{ 1, 0x00000000u, 0x0122fd02u },
	{ 1, 0x00000016u, 0x0121492au },
	{ 1, 0x00000000u, 0x0121fd01u },
	{ 1, 0x00000020u, 0x0121fd02u },
	{ 1, 0x00000045u, 0x0121fd03u },
	{ 1, 0x00000018u, 0x0121fd0cu },
	{ 1, 0x00000008u, 0x0121fd0cu },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd00u },
	{ 1, 0x00000000u, 0x0122fd02u },
	{ 1, 0x00000016u, 0x0121452au },
	{ 1, 0x00000000u, 0x0121fd01u },
	{ 1, 0x00000020u, 0x0121fd02u },
	{ 1, 0x00000049u, 0x0121fd03u },
	{ 1, 0x00000018u, 0x0121fd0cu },
	{ 1, 0x00000008u, 0x0121fd0cu },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd00u },
	{ 1, 0x00000000u, 0x0122fd02u },
	{ 1, 0x0000000eu, 0x0121492au },
	{ 1, 0x00000000u, 0x0121fd01u },
	{ 1, 0x00000020u, 0x0121fd02u },
	{ 1, 0x00000045u, 0x0121fd03u },
	{ 1, 0x00000018u, 0x0121fd0cu },
	{ 1, 0x00000008u, 0x0121fd0cu },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd00u },
	{ 1, 0x00000000u, 0x0122fd02u },
	{ 1, 0x0000000eu, 0x0121452au },
	{ 1, 0x00000000u, 0x0121fd01u },
	{ 1, 0x00000020u, 0x0121fd02u },
	{ 1, 0x00000049u, 0x0121fd03u },
	{ 1, 0x00000018u, 0x0121fd0cu },
	{ 1, 0x00000008u, 0x0121fd0cu },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd00u },
	{ 1, 0x00000000u, 0x0122fd02u },
	{ 1, 0x00000016u, 0x0121492au },
	{ 1, 0x00000000u, 0x0121fd01u },
	{ 1, 0x00000020u, 0x0121fd02u },
	{ 1, 0x00000045u, 0x0121fd03u },
	{ 1, 0x00000018u, 0x0121fd0cu },
	{ 1, 0x00000008u, 0x0121fd0cu },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd00u },
	{ 1, 0x00000000u, 0x0122fd02u },
	{ 1, 0x00000016u, 0x0121452au },
	{ 1, 0x00000000u, 0x0121fd01u },
	{ 1, 0x00000020u, 0x0121fd02u },
	{ 1, 0x00000049u, 0x0121fd03u },
	{ 1, 0x00000018u, 0x0121fd0cu },
	{ 1, 0x00000008u, 0x0121fd0cu },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd00u },
	{ 1, 0x00000000u, 0x0122fd02u },
	{ 1, 0x0000000eu, 0x0121492au },
	{ 1, 0x00000000u, 0x0121fd01u },
	{ 1, 0x00000020u, 0x0121fd02u },
	{ 1, 0x00000045u, 0x0121fd03u },
	{ 1, 0x00000018u, 0x0121fd0cu },
	{ 1, 0x00000008u, 0x0121fd0cu },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd00u },
	{ 1, 0x00000000u, 0x0122fd02u },
	{ 1, 0x0000000eu, 0x0121452au },
	{ 1, 0x00000000u, 0x0121fd01u },
	{ 1, 0x00000020u, 0x0121fd02u },
	{ 1, 0x00000049u, 0x0121fd03u },
	{ 1, 0x00000018u, 0x0121fd0cu },
	{ 1, 0x00000008u, 0x0121fd0cu },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd00u },
	{ 1, 0x00000000u, 0x0122fd02u },
	{ 1, 0x00000016u, 0x0121492au },
	{ 1, 0x00000000u, 0x0121fd01u },
	{ 1, 0x00000020u, 0x0121fd02u },
	{ 1, 0x00000045u, 0x0121fd03u },
	{ 1, 0x00000018u, 0x0121fd0cu },
	{ 1, 0x00000008u, 0x0121fd0cu },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd00u },
	{ 1, 0x00000000u, 0x0122fd02u },
	{ 1, 0x00000016u, 0x0121452au },
	{ 1, 0x00000000u, 0x0121fd01u },
	{ 1, 0x00000020u, 0x0121fd02u },
	{ 1, 0x00000049u, 0x0121fd03u },
	{ 1, 0x00000018u, 0x0121fd0cu },
	{ 1, 0x00000008u, 0x0121fd0cu },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd00u },
	{ 1, 0x00000000u, 0x0122fd02u },
	{ 1, 0x0000000eu, 0x0121492au },
	{ 1, 0x00000000u, 0x0121fd01u },
	{ 1, 0x00000020u, 0x0121fd02u },
	{ 1, 0x00000045u, 0x0121fd03u },
	{ 1, 0x00000018u, 0x0121fd0cu },
	{ 1, 0x00000008u, 0x0121fd0cu },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd00u },
	{ 1, 0x00000000u, 0x0122fd02u },
	{ 1, 0x0000000eu, 0x0121452au },
	{ 1, 0x00000000u, 0x0121fd01u },
	{ 1, 0x00000020u, 0x0121fd02u },
	{ 1, 0x00000049u, 0x0121fd03u },
	{ 1, 0x00000018u, 0x0121fd0cu },
	{ 1, 0x00000008u, 0x0121fd0cu },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd00u },
	{ 1, 0x00000000u, 0x0122fd02u },
	{ 1, 0x00000016u, 0x0121492au },
	{ 1, 0x00000000u, 0x0121fd01u },
	{ 1, 0x00000020u, 0x0121fd02u },
	{ 1, 0x00000045u, 0x0121fd03u },
	{ 1, 0x00000018u, 0x0121fd0cu },
	{ 1, 0x00000008u, 0x0121fd0cu },
	{ 1, 0x00000000u, 0x0122fd01u },
	{ 1, 0x00000000u, 0x0122fd00u },
	{ 1, 0x00000000u, 0x0122fd02u },
	{ 1, 0x00000016u, 0x0121452au },
};

/* the program: {first transaction, length, repeat count} */
static const uint16_t U[][3] = {
	{    0, 64,    1 },
	{   64,  8,   76 },
	{   72,  3,    1 },
	{   75, 64,    1 },
	{  139, 15,    1 },
	{  154,  2,    1 },
	{  156,  2,    1 },
	{  158, 26,    1 },
	{  184, 14,    1 },
	{  198, 31,    1 },
	{  229, 18,    1 },
	{  247, 36,    5 },
	{  283, 18,    1 },
	{  301, 36,    1 },
	{  337, 36,    4 },
	{  373, 18,    1 },
};

/* segments: {first unit, unit count} -- one per interleaved run */
static const uint16_t SEG[][2] = {
	{   0,   3 },
	{   3,   2 },
	{   5,   1 },
	{   6,   1 },
	{   7,   1 },
	{   8,   1 },
	{   9,   1 },
	{  10,   1 },
	{  11,   1 },
	{  12,   1 },
	{  13,   1 },
	{  14,   2 },
};

static int dry, list_only, nw, seg = -1;   /* -s N: emit run N only */
static long sbus_done, sbus_timeout;

/* Wait for the SBus to finish the transaction just issued: busy is bit 25 of
 * SBUS_COMMAND. This mirrors fm6000_fullreplay's sbus(), and it is not optional
 * -- without it Et2 went down on 5 boots out of 5. 0xffffffff means the chip is
 * off the bus, in which case there is nothing to wait for. */
static void sbus_wait(void)
{
	long i;
	if (dry || list_only) return;
	for (i = 0; i < 200000; i++) {
		uint32_t s = M[SBUS_COMMAND];
		__sync_synchronize();
		if (s == 0xffffffffu) return;
		if (!(s & (1u << 25))) { sbus_done++; return; }
	}
	sbus_timeout++;
}

static void emit(uint32_t addr, uint32_t val)
{
	if (list_only)   { printf("%08x\n", addr); return; }
	if (dry)         { printf("%08x %08x\n", addr, val); nw++; return; }
	M[addr] = val; __sync_synchronize(); nw++;
}

int main(int argc, char **argv)
{
	const char *bdf = "0000:02:00.0";
	int i; size_t u, r, t;

	for (i = 1; i < argc; i++) {
		if      (!strcmp(argv[i], "-n")) dry = 1;
		else if (!strcmp(argv[i], "-a")) list_only = 1;
		else if (!strcmp(argv[i], "-b") && i + 1 < argc) bdf = argv[++i];
		else if (!strcmp(argv[i], "-s") && i + 1 < argc) seg = atoi(argv[++i]);
		else { fprintf(stderr, "usage: %s [-n|-a] [-b bdf]\n", argv[0]); return 2; }
	}

	if (list_only) {
		/* Three addresses, each written many times. -a exists so make_residual
		 * can subtract what a generator covers; claiming these three is correct
		 * ONLY because this generator reproduces every write to them. */
		size_t k;
		uint32_t seen = 0;
		for (k = 0; k < sizeof(T) / sizeof(T[0]); k++)
			if (T[k][0] == 0 && !(seen & (1u << (T[k][1] & 0xf)))) {
				seen |= 1u << (T[k][1] & 0xf);
				printf("%08x\n", T[k][1]);
			}
		printf("%08x\n%08x\n", SBUS_REQUEST, SBUS_COMMAND);
		return 0;
	}

	if (!dry) {
		char path[256];
		int fd;
		snprintf(path, sizeof path, "/sys/bus/pci/devices/%s/resource0", bdf);
		fd = open(path, O_RDWR | O_SYNC);
		if (fd < 0) { perror("open resource0"); return 1; }
		M = mmap(NULL, 32u * 1024 * 1024, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
		if (M == MAP_FAILED) { perror("mmap"); return 1; }
	}

	{
		size_t ufirst = 0, ulast = sizeof(U) / sizeof(U[0]);
		if (seg >= 0) {
			if ((size_t)seg >= sizeof(SEG) / sizeof(SEG[0])) {
				fprintf(stderr, "fm6000_sbusseq: no segment %d (have %zu)\n",
				        seg, sizeof(SEG) / sizeof(SEG[0]));
				return 2;
			}
			ufirst = SEG[seg][0];
			ulast  = (size_t)(SEG[seg][0] + SEG[seg][1]);
		}
	for (u = ufirst; u < ulast; u++)
		for (r = 0; r < U[u][2]; r++)
			for (t = U[u][0]; t < (size_t)(U[u][0] + U[u][1]); t++) {
				/* REQUEST is written even when the payload is zero: the
				 * captured stream does, and a stale non-zero payload from
				 * the previous transaction would otherwise be reused. */
				if (T[t][0] == 0) { emit(T[t][1], T[t][2]); continue; }
				emit(SBUS_REQUEST, T[t][1]);
				emit(SBUS_COMMAND, 0);
				emit(SBUS_COMMAND, T[t][2]);
				sbus_wait();
			}

	}
	if (!dry) fprintf(stderr, "fm6000_sbusseq: %d writes, %ld transactions acked, "
	                  "%ld timed out\n", nw, sbus_done, sbus_timeout);
	return 0;
}
