/* fm6000_sweeperinit.c - program the SWEEPER block ourselves.
 *
 * GENERATED by asic/fm6000/tools/gen_tableinit.py -- do not edit by hand.
 *   gen_tableinit.py <replay> --name sweeper --range 00d000-00e000 --mode once
 *
 * L2L_SWEEPER: L2 table ageing sweeper
 *
 * Replaces 1362 replayed writes with 57 (54 non-zero).
 *
 * TABLE ONLY, deliberately: emits the 57 registers written exactly once
 * and leaves the 120 multi-write control registers in the replay with their
 * sequences intact. Collapsing those would destroy strobes -- the FFU's commit
 * pulse at 0x3f0000 fires 59 times, and one commit instead of 59 means the
 * CPU-punt traps never apply. `-a` prints the address list so the boot script
 * filters exactly these lines and nothing else.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later */
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdint.h>
#include <string.h>
#include <sys/mman.h>

static const uint32_t R[][2] = {
	{0x0000d000,0x00000000},
	{0x0000d001,0x00000001},
	{0x0000d080,0xffffffff},
	{0x0000d081,0xffffffff},
	{0x0000d082,0xffffffff},
	{0x0000d083,0xffffffff},
	{0x0000d084,0xffffffff},
	{0x0000d085,0xffff7fff},
	{0x0000d086,0xffffffff},
	{0x0000d087,0xffffffff},
	{0x0000d088,0xffffffff},
	{0x0000d089,0xffffffff},
	{0x0000d08a,0xffffffff},
	{0x0000d08b,0xffffffff},
	{0x0000d08c,0xffffffff},
	{0x0000d08d,0xffffdffe},
	{0x0000d08e,0xffffffff},
	{0x0000d08f,0xffff2ff3},
	{0x0000d090,0xffffffff},
	{0x0000d091,0xffffffff},
	{0x0000d092,0xffffffff},
	{0x0000d093,0xffffffff},
	{0x0000d094,0xffffffff},
	{0x0000d095,0xffffeffe},
	{0x0000d096,0xffffffff},
	{0x0000d097,0xffff1ff3},
	{0x0000d098,0xffffffff},
	{0x0000d099,0xffffffff},
	{0x0000d09a,0xffffffff},
	{0x0000d09b,0xffffffff},
	{0x0000d09c,0xffffffff},
	{0x0000d09d,0xffffdfff},
	{0x0000d09e,0xffffffff},
	{0x0000d09f,0xffff2ff2},
	{0x0000d0a0,0xffffffff},
	{0x0000d0a1,0xffffffff},
	{0x0000d0a2,0xffffffff},
	{0x0000d0a3,0xffffffff},
	{0x0000d0a4,0xffffffff},
	{0x0000d0a5,0xffffefff},
	{0x0000d0a6,0xffffffff},
	{0x0000d0a7,0xffff1ff2},
	{0x0000d100,0x24000000},
	{0x0000d101,0xffffffd0},
	{0x0000d102,0x001003f4},
	{0x0000d104,0x00000000},
	{0x0000d105,0xbfffffc0},
	{0x0000d106,0x00000fff},
	{0x0000d108,0x00000000},
	{0x0000d109,0xbfffffc0},
	{0x0000d10a,0x00000fff},
	{0x0000d10c,0x0c000000},
	{0x0000d10d,0xffffffc0},
	{0x0000d10e,0x00000ffc},
	{0x0000d110,0x0c000000},
	{0x0000d111,0xffffffc0},
	{0x0000d112,0x00000ffc},
};

int main(int argc, char **argv)
{
	const char *bdf = "0000:02:00.0";
	char p[256]; int fd, i, dry = 0, list = 0;
	volatile uint32_t *M = NULL;

	for (i = 1; i < argc; i++) {
		if (!strcmp(argv[i], "-n")) dry = 1;
		else if (!strcmp(argv[i], "-a")) list = 1;
		else bdf = argv[i];
	}
	if (list) {
		for (i = 0; i < (int)(sizeof R / sizeof R[0]); i++)
			printf("%08x\n", R[i][0]);
		return 0;
	}
	if (!dry) {
		snprintf(p, sizeof p, "/sys/bus/pci/devices/%s/resource0", bdf);
		fd = open(p, O_RDWR | O_SYNC);
		if (fd < 0) { perror("open"); return 1; }
		M = mmap(NULL, 32u*1024*1024, PROT_READ|PROT_WRITE, MAP_SHARED, fd, 0);
		if (M == MAP_FAILED) { perror("mmap"); return 1; }
	}
	for (i = 0; i < (int)(sizeof R / sizeof R[0]); i++) {
		if (dry) printf("%08x %08x\n", R[i][0], R[i][1]);
		else { M[R[i][0]] = R[i][1]; __sync_synchronize(); }
	}
	if (!dry)
		printf("fm6000_sweeperinit: %d writes\n",
		       (int)(sizeof R / sizeof R[0]));
	return 0;
}
