hostname edgenos-ospf
password zebra
log syslog
!
interface swp1
 ip ospf cost 40
interface swp2
 ip ospf cost 40
interface swp4
 ip ospf cost 40
interface swp49
 ip ospf cost 10
!
router ospf
 ospf router-id 10.101.101.241
 passive-interface lo
 network 10.101.101.0/29 area 0.0.0.0
 network 10.101.101.8/29 area 0.0.0.0
 network 10.101.101.16/29 area 0.0.0.0
 network 10.101.101.241/32 area 0.0.0.0
 network 10.101.102.0/29 area 0.0.0.0
