hostname ospf6d
password zebra
log syslog
!
router ospf6
 router-id 10.101.101.241
 interface lo area 0.0.0.0
 interface swp1 area 0.0.0.0
 interface swp2 area 0.0.0.0
 interface swp4 area 0.0.0.0
 interface swp49 area 0.0.0.0
 interface swp6 area 0.0.0.0
