#!/bin/bash
# Generate config.bcm for a DCS-7050SX2-72Q from YOUR OWN switch.
#
# WHY THIS TOOL EXISTS
# --------------------
# The SDK cannot bring a single port up without a port map: which logical port
# is wired to which physical SerDes lane, and which MMU port serves it. That
# map is a property of the BOARD, but no public document publishes it for this
# machine -- it is a 2017-era EOS-only box, absent from Arista's open SONiC
# platform tree and from sonic-buildimage, and no open config.bcm for it exists
# anywhere (searched: sonic-net, aristanetworks, and every open .bcm mentioning
# 56860 -- all of those are the SDK's own generic rc/config.bcm).
#
# So the map has to be read from the vendor's software on the machine that has
# it. That makes it vendor-derived, so it is NOT shipped with EdgeNOS. You
# generate it once, on your own switch, and it stays yours.
#
# Same arrangement as tools/mkpolarity.sh, and as the 7050TX-64 platform's
# cooling curve and retimer values: the mechanism is ours and public, the
# vendor's numbers are read from the machine that already has them.
#
# USAGE
#   ./mkconfigbcm.sh <switch-ip> > config.bcm          # portmap only
#   POLARITY=1 ./mkconfigbcm.sh <switch-ip> > config.bcm   # also run mkpolarity
#
# Environment: SW_USER (default admin), SW_PW (default arista).
#
# READ-ONLY. `show platform trident system detail` is a show command; with
# POLARITY=1 the polarity pass is register reads only. Nothing is written.
set -u
SW=${1:?usage: mkconfigbcm.sh <switch-ip>}
USER=${SW_USER:-admin}
PW=${SW_PW:-arista}
HERE=$(cd "$(dirname "$0")" && pwd)

SSHOPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
-o ConnectTimeout=10 -o HostKeyAlgorithms=+ssh-rsa
-o PubkeyAcceptedKeyTypes=+ssh-rsa
-o KexAlgorithms=+diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1"

# EOS prints the whole mapping in one table:
#
#                       Port
#    Intf        Chip      ModId   Logical   Physical  MMU
#   Ethernet1  Linecard0/0     1         1         13    1
#   Ethernet2  Linecard0/0     1         2         14   12
#
# Logical is the SDK's port number, Physical is the SerDes lane the SDK wants in
# portmap_<logical>=<physical>:<speed>. MMU is carried through as a comment
# because it is what the TDM calendar is keyed on and is worth being able to
# check against later.
RAW=$(sshpass -p "$PW" ssh $SSHOPTS "$USER@$SW" \
        "enable
terminal length 0
show platform trident system detail" 2>/dev/null | tr -d '\r')

MAP=$(printf '%s\n' "$RAW" | awk '
    # UnconnectedEthernetN are ASIC ports with no front-panel connector. They
    # are NOT optional: they occupy MMU ports (0, 71-75 on this board) and the
    # TDM calendar is built over the full set, so omitting them leaves six
    # holes in the port map the SDK was given.
    /^ *(Unconnected)?Ethernet[0-9]+/ {
        # Intf Chip ModId Logical Physical MMU
        if (NF >= 6 && $4 ~ /^[0-9]+$/ && $5 ~ /^[0-9]+$/ && $6 ~ /^[0-9]+$/)
            print $4, $5, $6, $1
    }')

if [ -z "$MAP" ]; then
    echo "ERROR: could not read the port map from $SW." >&2
    echo "       Expected 'show platform trident system detail' to print an" >&2
    echo "       Intf/Chip/ModId/Logical/Physical/MMU table. Raw output:" >&2
    printf '%s\n' "$RAW" | head -20 >&2
    exit 1
fi

NPORT=$(printf '%s\n' "$MAP" | wc -l)
MAXLOG=$(printf '%s\n' "$MAP" | awk '{if ($1+0 > m) m = $1+0} END {print m}')

cat <<HDR
# BCM56860 (Trident2+) on an Arista DCS-7050SX2-72Q-R.
#
# Generated by tools/mkconfigbcm.sh from $SW on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# $NPORT ports, highest logical port $MAXLOG.
#
# The port map below was read from this switch's own EOS installation and is
# specific to this board. It is deliberately not distributed with EdgeNOS --
# regenerate it on your own machine.

# The shim connects no interrupt, so the SDK has to be told to poll.
# soc_attach() otherwise fails at drv.c:21184, 'could not connect interrupt
# line': a failing interrupt_connect is only tolerated when polled_irq_mode is
# set, and then the SDK runs its own polling thread (soc_ipoll_connect).
polled_irq_mode=1
miim_intr_enable=0

# Every front-panel port on this box is a fixed 10G optical link. Autoneg off
# and an explicit speed keeps the SDK from negotiating on a link that has
# nothing to negotiate with.
port_init_autoneg=0
port_init_duplex=1
port_init_speed=10000
HDR

# Every logical port 1..MAXLOG is an xe port on this board. The SDK wants that
# as a bitmap; bit N means logical port N. Computed rather than hard-coded so a
# board with a different port count still comes out right.
python3 - "$MAXLOG" <<'PY'
import sys
n = int(sys.argv[1])
bits = 0
for i in range(1, n + 1):
    bits |= 1 << i
print("pbmp_xport_xe=0x%x" % bits)
PY

echo
echo "# --- port map: logical -> physical SerDes lane, 10G each ---"
printf '%s\n' "$MAP" | sort -n | while read -r logical physical mmu intf; do
    printf 'portmap_%s=%s:10   # %s, MMU port %s\n' "$logical" "$physical" "$intf" "$mmu"
done

echo
echo "# --- per-lane SerDes: DFE on, optical media ---"
echo "# Our choice, not read from the switch: every front-panel port on this"
echo "# box is SFP+/QSFP optical, and DFE is what the SDK wants for a passive"
echo "# optical link. Not board-specific."
printf '%s\n' "$MAP" | sort -n | while read -r logical physical mmu intf; do
    printf 'serdes_lane_config_dfe_%s=on\n'          "$logical"
    printf 'serdes_lane_config_media_type_%s=optics\n' "$logical"
done

cat <<'LANEMAP'

# --- SerDes TX lane map ---
#
# OURS, MEASURED -- not read from the switch, so it is emitted as a constant.
#
# 0x0123 is 0x3210 pre-complemented. With it set, blocks 18/20/21/22/23 come up
# with d0fb/d0fc matching the reference platform and Et1 transmits losslessly
# from a cold init: chip TX 169, far end 170. Removing it puts the port back to
# chip TX 170, far end 0 -- i.e. transmitting into nothing.
xgxs_tx_lane_map_core=0x0123

# Per-macro exceptions: these blocks want the SDK's 0x3210 default instead.
#
# ⚠ THE VALUES ARE OURS; THE PORT LIST IS BOARD-SPECIFIC. Which blocks need the
#   exception was determined on a DCS-7050SX2-72Q by comparing the resulting
#   d0fb against the vendor software's. On a different board -- or if links come
#   up carrying garbage on some ports and not others -- re-derive it by reading
#   TX lane map registers 0xd0fb/0xd0fc per macro and finding the property that
#   reproduces them. Do not assume this list transfers.
xgxs_tx_lane_map_core0_57=0x3210
xgxs_tx_lane_map_core0_58=0x3210
xgxs_tx_lane_map_core0_59=0x3210
xgxs_tx_lane_map_core0_60=0x3210
xgxs_tx_lane_map_core0_61=0x3210
xgxs_tx_lane_map_core0_62=0x3210
xgxs_tx_lane_map_core0_63=0x3210
xgxs_tx_lane_map_core0_64=0x3210
xgxs_tx_lane_map_core0_73=0x3210
xgxs_tx_lane_map_core0_76=0x3210
xgxs_tx_lane_map_core0_78=0x3210

# The QSFP blocks 42 and 45 are deliberately absent. Two derived values were
# tried and both were REFUTED against the reference d0fb (0x2031 gave 0x0061,
# not 0x0c02; 0x3021 gave 0x0861, not 0x0c22), so the parity is not understood
# per macro. Guessing here brings a link up carrying garbage, which is worse
# than leaving it down -- so it is left at the global until measured.
LANEMAP

cat <<'PREEMPH'

# --- transmit equaliser (serdes_preemphasis) is NOT emitted ---
#
# NOT load-bearing: without it the SDK falls through to the chip's reset TX FIR
# and links still come up and pass traffic. What it changes is signal quality,
# not correctness -- the transmit fault on this board was polarity, and
# preemphasis did not fix it and was kept because it is right, not because it
# helped.
#
# It is omitted because the values are the vendor's. The ENCODING is public --
# src/soc/phy/tsce.c in the OpenBCM SDK reads the property as
#
#     pre  =  preemphasis & 0xff
#     main = (preemphasis & 0xff00) >> 8
#     post = (preemphasis & 0xff0000) >> 16
#
# so the property is (post << 16) | (main << 8) | pre, and the lane number is
# the physical lane, core*4 + lane, covering 0..95 on this chip.
#
# To match your vendor software's tuning, read what it programs into the TXFIR
# registers (0xd110 onward per macro/lane) on your own switch and encode it as
# above. Deriving post from those registers is NOT straightforward -- the low 7
# bits of 0xd110 are main, but the remaining field did not decode cleanly here,
# so this is left to whoever needs it rather than guessed at.
#
# If every cabled port uses identical optics, one value repeated across all 96
# lanes is what the vendor does:
#     serdes_preemphasis_lane0=0x00<post><main><pre>
#     ... through lane95
PREEMPH

if [ "${POLARITY:-0}" = 1 ]; then
    echo
    if [ -x "$HERE/mkpolarity.sh" ]; then
        SW_USER="$USER" SW_PW="$PW" "$HERE/mkpolarity.sh" "$SW" || {
            echo "# ERROR: mkpolarity.sh failed -- polarity NOT included." >&2
            exit 1
        }
    else
        echo "# ERROR: mkpolarity.sh not found next to this script." >&2
        exit 1
    fi
else
    cat <<'TAIL'

# --- SerDes polarity is NOT included above ---
#
# Without it links will come up and carry garbage: inverting a 64b/66b stream
# turns the sync header 01 into 10, which is also legal, so the receiver locks
# onto nonsense rather than reporting a fault. Append the table with:
#
#     ./mkpolarity.sh <switch-ip> >> config.bcm
#
# or re-run this script as  POLARITY=1 ./mkconfigbcm.sh <switch-ip>
TAIL
fi
