#!/bin/bash
# Generate this board's chassis status LED map from YOUR OWN switch.
#
# WHY THIS TOOL EXISTS
# --------------------
# The 7050SX2's chassis LEDs -- system status, the two PSU lamps, the fan lamp
# and the blue locator beacon -- are not on the SCD. They are registers on the
# StandbyCpld that also runs the fans, and unlike the SCD offsets and the fan
# registers, these five are NOT in anything Arista publishes. They come from the
# board description file that ships on the switch, which is vendor material.
#
# So EdgeNOS ships the mechanism and not the numbers. Run this once against your
# own switch, keep the header it prints, and build with it. Same arrangement as
# mkconfigbcm.sh and mkpolarity.sh, and the same reason.
#
# Everything the mechanism needs beyond these five offsets is already public:
# the CPLD answers at 0x60 on SMBus accelerator 0 bus 0, which Arista's own
# arista/platforms/cpu/crow.py gives as CrowFanCpld addr=scd.i2cAddr(bus, 0x60).
#
# USAGE
#   ./mkstatusleds.sh <switch-ip> > tools/crow-statusled-map.h
#
# Environment: SW_USER (default admin), SW_PW (default arista).
#
# READ-ONLY. This reads three text files off the switch. It issues no register
# access at all, let alone to the CPLD -- sweeping that part has powered this
# box off twice, and nothing here goes near it.
set -u
SW=${1:?usage: mkstatusleds.sh <switch-ip> > crow-statusled-map.h}
USER=${SW_USER:-admin}
PW=${SW_PW:-arista}

SSHOPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
-o ConnectTimeout=10 -o HostKeyAlgorithms=+ssh-rsa
-o PubkeyAcceptedKeyTypes=+ssh-rsa
-o KexAlgorithms=+diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1"

sw() { sshpass -p "$PW" ssh $SSHOPTS "$USER@$SW" "enable
bash $*" 2>/dev/null | tr -d '\r'; }

die() { echo "mkstatusleds: $*" >&2; exit 1; }

# 1. Which board is this? The SID in the programmed prefdl IS the FDL name.
SID=$(sw "grep -i '^SID:' /etc/prefdl | head -1 | cut -d: -f2 | tr -d ' '")
[ -n "$SID" ] || die "could not read SID from /etc/prefdl on $SW"

# 2. Which classes does it inherit? The Genfdl plugin for the CPU family maps
#    (SID, hwrev) -> a list of FDL classes, and the LED table lives in a parent,
#    not in the board's own file. Search every plugin rather than assuming which
#    family this board belongs to.
CLASSES=$(sw "grep -h \"'$SID'\" -A3 /usr/lib/python*/site-packages/GenfdlPlugin/*.py \
             | tr -d \"\\n\" | tr ']' '\\n' | grep -m1 \"'$SID'\" | tr -d \"[]',\"")
[ -n "$CLASSES" ] || die "no Genfdl entry for SID '$SID'"

# 3. The LED table. addLeds() lists ( description, addr, greenBit, redBit ) and
#    a comment gives the blue beacon's own register. Take the first class that
#    has one -- the board's own file inherits it.
TABLE=""
for c in $CLASSES; do
    case "$c" in *:*|*\(*) continue;; esac
    t=$(sw "sed -n '/def addLeds/,/def /p' /usr/share/NorCal/$c.fdl 2>/dev/null")
    if echo "$t" | grep -q 'cpldLedBlock\|cpldLedInfo'; then TABLE="$t"; FDL="$c"; break; fi
done
[ -n "$TABLE" ] || die "no addLeds() with a CPLD LED table in: $CLASSES"

get() { echo "$TABLE" | grep -oE "\(\s*\"$1\"\s*,\s*0x[0-9a-fA-F]+\s*,\s*[0-9]+\s*,\s*[0-9]+\s*\)" | head -1; }
field() { echo "$1" | tr -d '() "' | cut -d, -f"$2"; }

S=$(get Status1); P1=$(get PowerSupply1); P2=$(get PowerSupply2); F=$(get MultiFan1)
[ -n "$S" ] || die "no Status1 entry in $FDL addLeds()"

BEACON=$(echo "$TABLE" | grep -oE 'blueLedOffset\s*=\s*0x[0-9a-fA-F]+' | grep -oE '0x[0-9a-fA-F]+' | head -1)
BEACONBIT=$(echo "$TABLE" | grep -oE 'blueBit\s*=\s*[0-9]+' | grep -oE '[0-9]+$' | head -1)
: "${BEACONBIT:=0}"

cat <<EOF
/* Chassis status LED map for $SID, read from $FDL.fdl on a live switch.
 *
 * GENERATED by tools/mkstatusleds.sh -- do not edit, and do not publish. These
 * offsets are vendor board-description data; the tool that regenerates them is
 * what ships. Rerun it against your own switch to recreate this file.
 */
#ifndef CROW_STATUSLED_MAP_H
#define CROW_STATUSLED_MAP_H

#define CROW_STATUSLED_MAP_PRESENT 1
#define CROW_LED_STATUS  $(field "$S" 2)u
#define CROW_LED_PSU1    $(field "$P1" 2)u
#define CROW_LED_PSU2    $(field "$P2" 2)u
#define CROW_LED_FAN     $(field "$F" 2)u
#define CROW_LED_BEACON  ${BEACON:-0x00}u
#define LED_GREEN_BIT    $(field "$S" 3)
#define LED_RED_BIT      $(field "$S" 4)
#define LED_BLUE_BIT     $BEACONBIT

#endif
EOF
