#!/bin/sh
# EdgeNOS ONIE installer — x86_64, self-extracting.
#
# Generated by imgbuild (packaging/imgbuild.py) from packaging/installer/onie-x86/install.sh;
# a tar payload (bzImage, initrd.img, rootfs.sqsh, grub.cfg, bootx64.efi) follows the
# __ARCHIVE_BELOW__ marker. Runs under ONIE (busybox sh) on a legacy-BIOS or UEFI box:
#
#   onie-nos-install http://<server>/EdgeNOS-<ver>-<platform>.bin
#
# Layout it creates on the ONIE disk (GPT, after ONIE's own partitions):
#   EDGENOS-BOOT  ext4  BOOT_SIZE_MB   /edgenos/{bzImage,initrd.img,rootfs.sqsh} + /grub/grub.cfg
#   EDGENOS-DATA  ext4  rest of disk   overlay upper (persistence)
# Bootloader: UEFI -> our GRUB (bootx64.efi, embedded label search) copied to the ESP
# as \EFI\EdgeNOS\grubx64.efi + efibootmgr entry; BIOS -> ONIE's grub-install pointed at
# EDGENOS-BOOT/grub. Either way the menu is EDGENOS-BOOT:/grub/grub.cfg (with an ONIE entry).
NOS_NAME="EdgeNOS"
NOS_VERSION="@VERSION@"
NOS_PLATFORM="@PLATFORM@"
BOOT_LABEL="EDGENOS-BOOT"
DATA_LABEL="EDGENOS-DATA"
BOOT_SIZE_MB="${BOOT_SIZE_MB:-512}"
DATA_SIZE_MB="${DATA_SIZE_MB:-0}"        # 0 = the rest of the disk
ESP_DIR="EdgeNOS"

set -e
say()  { echo "$NOS_NAME: $*"; }
fail() { echo "$NOS_NAME: ERROR: $*" >&2; exit 1; }

say "installer $NOS_VERSION for $NOS_PLATFORM"

# --- environment sanity ---------------------------------------------------------------
command -v onie-sysinfo >/dev/null 2>&1 || say "warning: onie-sysinfo not found (not running under ONIE?)"
if command -v onie-sysinfo >/dev/null 2>&1; then
    here=$(onie-sysinfo -p 2>/dev/null || true)
    if [ -n "$here" ] && [ "$here" != "$NOS_PLATFORM" ] && [ -z "$EDGENOS_FORCE" ]; then
        case "$here" in
            x86_64-*) say "platform is $here (image targets $NOS_PLATFORM); generic x86_64 image, continuing" ;;
            *)        fail "platform $here is not x86_64; refusing (set EDGENOS_FORCE=1 to override)" ;;
        esac
    fi
fi
for t in sgdisk blkid mkfs.ext4 tar; do
    command -v "$t" >/dev/null 2>&1 || fail "missing tool: $t"
done
rereadpt() {   # tell the kernel about the new partition table
    partprobe "$1" 2>/dev/null || blockdev --rereadpt "$1" 2>/dev/null || sgdisk -p "$1" >/dev/null 2>&1 || true
    sleep 2
}

if [ -d /sys/firmware/efi/efivars ]; then FW=uefi; else FW=bios; fi
say "firmware: $FW"

# --- the install disk: the one carrying ONIE-BOOT ----------------------------------------
onie_part=$(blkid -L ONIE-BOOT 2>/dev/null || true)
[ -n "$onie_part" ] || onie_part=$(blkid | sed -n 's/^\([^:]*\):.*LABEL="ONIE-BOOT".*/\1/p' | head -1)
[ -n "$onie_part" ] || fail "cannot find the ONIE-BOOT partition"
case "$onie_part" in
    /dev/nvme*|/dev/mmcblk*) disk=$(echo "$onie_part" | sed 's/p[0-9]*$//') ;;
    *)                       disk=$(echo "$onie_part" | sed 's/[0-9]*$//') ;;
esac
say "install disk: $disk (ONIE-BOOT on $onie_part)"

partdev() {   # partdev <disk> <n>
    case "$1" in /dev/nvme*|/dev/mmcblk*) echo "$1p$2" ;; *) echo "$1$2" ;; esac
}

# --- remove a previous EdgeNOS install (by partition label), keep everything else ------
for lbl in "$BOOT_LABEL" "$DATA_LABEL"; do
    old=$(blkid | sed -n "s/^\([^:]*\):.*LABEL=\"$lbl\".*/\1/p")
    for p in $old; do
        n=$(echo "$p" | sed 's/.*[a-z]\([0-9]*\)$/\1/')
        say "removing old $lbl partition $p"
        sgdisk -d "$n" "$disk" >/dev/null
    done
done
rereadpt "$disk"

# --- create EDGENOS-BOOT + EDGENOS-DATA --------------------------------------------------
next=$(sgdisk -p "$disk" | awk '/^ *[0-9]+ /{n=$1} END{print n+1}')
say "creating $BOOT_LABEL (${BOOT_SIZE_MB}M) as partition $next"
sgdisk --new="$next:0:+${BOOT_SIZE_MB}M" --typecode="$next:8300" --change-name="$next:$BOOT_LABEL" "$disk" >/dev/null
boot_n=$next; next=$((next + 1))
if [ "$DATA_SIZE_MB" = "0" ]; then dsz="0"; else dsz="+${DATA_SIZE_MB}M"; fi
say "creating $DATA_LABEL ($([ "$dsz" = 0 ] && echo 'rest of disk' || echo "${DATA_SIZE_MB}M")) as partition $next"
sgdisk --new="$next:0:$dsz" --typecode="$next:8300" --change-name="$next:$DATA_LABEL" "$disk" >/dev/null
data_n=$next
rereadpt "$disk"
boot_dev=$(partdev "$disk" "$boot_n"); data_dev=$(partdev "$disk" "$data_n")
i=0; while [ ! -b "$boot_dev" ] || [ ! -b "$data_dev" ]; do i=$((i+1)); [ $i -gt 20 ] && fail "partitions did not appear"; sleep 0.5; done

mkfs.ext4 -q -F -L "$BOOT_LABEL" "$boot_dev"
mkfs.ext4 -q -F -L "$DATA_LABEL" "$data_dev"

# --- payload -> EDGENOS-BOOT -------------------------------------------------------------
mnt=/tmp/edgenos-boot; mkdir -p "$mnt"; mount "$boot_dev" "$mnt"
mkdir -p "$mnt/edgenos" "$mnt/grub"
say "extracting payload to $boot_dev"
sed -e '1,/^__ARCHIVE_BELOW__$/d' "$0" | tar xf - -C "$mnt/edgenos"
mv "$mnt/edgenos/grub.cfg" "$mnt/grub/grub.cfg"
mkdir -p "$mnt/boot/grub" && cp "$mnt/grub/grub.cfg" "$mnt/boot/grub/grub.cfg"   # prefix-style fallback path
echo "$NOS_VERSION" > "$mnt/edgenos/VERSION"
sync

# --- bootloader --------------------------------------------------------------------------
if [ "$FW" = uefi ]; then
    # The ESP: ONIE mounts it at /boot/efi in UEFI mode; otherwise find it by GPT type code
    # (busybox blkid prints no TYPE=, so don't rely on that) or by its "EFI System" label.
    esp=$(awk '$2=="/boot/efi"{print $1; exit}' /proc/mounts)
    em=""
    if [ -n "$esp" ]; then
        em=/boot/efi; mounted_esp=1
    else
        esp_n=$(sgdisk -p "$disk" | awk '$6=="EF00"{print $1; exit}')
        [ -n "$esp_n" ] || esp_n=$(blkid | sed -n "s|^$disk\([0-9p]*\):.*LABEL=\"EFI System\".*|\1|p" | sed 's/^p//' | head -1)
        [ -n "$esp_n" ] || fail "no EFI System Partition found on $disk"
        esp=$(partdev "$disk" "$esp_n")
        em=/tmp/edgenos-esp; mkdir -p "$em"; mount "$esp" "$em" || fail "cannot mount ESP $esp"
        mounted_esp=0
    fi
    esp_n=$(echo "$esp" | sed 's/.*[a-z]\([0-9]*\)$/\1/')
    mkdir -p "$em/EFI/$ESP_DIR"
    cp "$mnt/edgenos/bootx64.efi" "$em/EFI/$ESP_DIR/grubx64.efi"
    sync
    [ "$mounted_esp" = 1 ] || umount "$em"
    if command -v efibootmgr >/dev/null 2>&1; then
        for b in $(efibootmgr | sed -n "s/^Boot\([0-9A-F]\{4\}\)\*\? *$NOS_NAME.*/\1/p"); do
            efibootmgr -q -b "$b" -B || true
        done
        efibootmgr -q -c -d "$disk" -p "$esp_n" -L "$NOS_NAME" -l "\\EFI\\$ESP_DIR\\grubx64.efi" \
            || say "warning: efibootmgr failed; boot \\EFI\\$ESP_DIR\\grubx64.efi manually"
    else
        say "warning: efibootmgr not available; add \\EFI\\$ESP_DIR\\grubx64.efi to the boot order manually"
    fi
    say "UEFI: installed \\EFI\\$ESP_DIR\\grubx64.efi on $esp"
else
    command -v grub-install >/dev/null 2>&1 || fail "grub-install not available in this ONIE (BIOS install needs it)"
    grub-install --boot-directory="$mnt" --recheck "$disk" >/dev/null 2>&1 \
        || grub-install --boot-directory="$mnt" "$disk" \
        || fail "grub-install failed"
    say "BIOS: GRUB installed to $disk -> $BOOT_LABEL:/grub"
fi
rm -f "$mnt/edgenos/bootx64.efi"
sync; umount "$mnt"

# tell ONIE a NOS is installed (stops auto-discovery on next boot)
command -v onie-nos-mode >/dev/null 2>&1 && onie-nos-mode -s >/dev/null 2>&1 || true

say "install complete: $NOS_NAME $NOS_VERSION on $disk ($BOOT_LABEL=$boot_dev, $DATA_LABEL=$data_dev). Rebooting into $NOS_NAME."
exit 0
__ARCHIVE_BELOW__
