#!/bin/sh
# fdl-extract.sh -- generate this board's runtime configuration from its OWN FDL.
#
# WHY THIS EXISTS
#
# Two things this platform needs are the board vendor's data, not ours: the
# cooling curve and the DS100KR800 retimer's tuning values. Both live in
# `/etc/fdl` on the switch, which is Arista Confidential -- so the code that uses
# them is published and the numbers are not. This script is the bridge: run it on
# your own switch, against your own board's description, and it emits the two
# configuration files the platform reads at runtime.
#
# Nothing here is secret. The FDL is on the box you own; this just parses it.
#
# Usage:
#   fdl-extract.sh cooling  > /etc/edgenos/cooling.conf
#   fdl-extract.sh retimer  > /etc/edgenos/retimer.conf
#   fdl-extract.sh all           # writes both into /etc/edgenos
#
# ⚠ Do not commit the output to a public repository, and never commit /etc/fdl
# itself. The output is derived from a confidential file; treat it the same way.
set -u

FDL="${EDGENOS_FDL:-/etc/fdl}"
OUTDIR="${EDGENOS_CONFDIR:-/etc/edgenos}"

[ -r "$FDL" ] || { echo "** cannot read $FDL" >&2; exit 1; }

# Airflow decides which curve applies. The FDL carries both a forward
# (front-to-back) and a reverse (back-to-front) table; the reverse one is for
# intake-at-the-back chassis. Override with EDGENOS_AIRFLOW=forward.
airflow="${EDGENOS_AIRFLOW:-reverse}"

emit_cooling() {
    echo "# Generated by fdl-extract.sh from $FDL -- $airflow airflow."
    echo "# Derived from the board's own description. Do not publish."
    echo
    # e.g.  reverseInletTempToCoolingLevel = { 25: 2, 31.66: 3, 36.66: 4, 40: 5 }
    sed -n "s/^${airflow}InletTempToCoolingLevel[[:space:]]*=[[:space:]]*{\(.*\)}.*/\1/p" "$FDL" \
        | tr ',' '\n' \
        | sed -n 's/[[:space:]]*\([0-9.]\+\)[[:space:]]*:[[:space:]]*\([0-9.]\+\).*/curve \1 \2/p'
    echo
    sed -n "s/^${airflow}CoolingLevelToFanSpeed[[:space:]]*=[[:space:]]*{\(.*\)}.*/\1/p" "$FDL" \
        | tr ',' '\n' \
        | sed -n 's/[[:space:]]*\([0-9.]\+\)[[:space:]]*:[[:space:]]*\([0-9.]\+\).*/speed \1 \2/p'
}

# ds100KrData is a list of ('name', value) tuples. Channels 0-3 and 4-7 are
# tuned separately on this board, so take one representative of each half.
fdl_reg() {
    sed -n "s/.*('$1',[[:space:]]*\([0-9]\+\)).*/\1/p" "$FDL" | head -1
}
hex() { [ -n "$1" ] && printf '0x%02x\n' "$1" || echo ""; }

emit_retimer() {
    echo "# Generated by fdl-extract.sh from $FDL (ds100KrData)."
    echo "# Derived from the board's own description. Do not publish."
    echo
    echo "pin_control  $(hex "$(fdl_reg pinControl)")"
    echo "disable_crc  $(hex "$(fdl_reg disableCrc)")"
    echo "eq           $(hex "$(fdl_reg rxEqualizationCh0)")"
    echo "vod_low      $(hex "$(fdl_reg outputAmplitudeCh0)")"
    echo "vod_high     $(hex "$(fdl_reg outputAmplitudeCh4)")"
    echo "dem_low      $(hex "$(fdl_reg txDeEmphasisCh0)")"
    echo "dem_high     $(hex "$(fdl_reg txDeEmphasisCh4)")"
}

case "${1:-all}" in
    cooling) emit_cooling ;;
    retimer) emit_retimer ;;
    all)
        mkdir -p "$OUTDIR"
        emit_cooling > "$OUTDIR/cooling.conf"
        emit_retimer > "$OUTDIR/retimer.conf"
        echo "wrote $OUTDIR/cooling.conf and $OUTDIR/retimer.conf" >&2
        ;;
    *) echo "usage: fdl-extract.sh [cooling|retimer|all]" >&2; exit 2 ;;
esac
