#!/usr/bin/env python3
"""mkconfigbcm.py -- turn a captured EOS SDK config dump into a config.bcm.

The SDK will not attach without properties: with none set, `soc_attach` fails
with "Port config error !!" and `soc_cm_device_init` returns -2, because it
cannot build a port map. We do not have to invent one -- `platform trident diag
config` on the running EOS box prints the live property set, captured in
artifacts/golden-20260816-40g/asic-config.txt.

Two transforms are needed:

  1. Strip the leading indent the CLI adds.
  2. Remap the unit suffix. EOS drives this chip as **unit 1**; our sdkpoc gets
     unit 0 from soc_cm_device_create, and a property tagged `.1` is invisible
     to unit 0. Every `name.1=` therefore becomes `name.0=`.

Note the trailing `.N` is the SDK's *unit* qualifier, not part of the name --
`portmap_46.1` is "portmap_46 on unit 1", where the 46 IS part of the name.
Only the final component is rewritten.

⚠ EOS's FULL property set is not safe to feed the SDK wholesale: something in
it makes bcm_attach return -6 (BCM_E_FULL). Use --minimal, which keeps only what
the port layer actually needs and is the set proven to reach bcm_init rv=0:
portmap_*, os, pbmp_xport_xe, higig2_hdr_mode, plus the two we add ourselves.
Without pbmp_xport_xe the SDK brings every port up as HiGig (hg0..) instead of
Ethernet (xe0..).

Usage:
    mkconfigbcm.py <asic-config.txt> <config.bcm> [--unit N] [--minimal]
"""
import re
import sys

LINE = re.compile(r'^\s*([A-Za-z_][A-Za-z0-9_]*(?:\.[0-9]+)?)\s*=\s*(\S+)\s*$')

SKIP_PREFIXES = ("Pagination", "localhost", "!")

# Properties from EOS's set that are actively harmful to THIS SDK build, always
# dropped. Bisected on hardware -- see docs/PORT-LAYER-INVESTIGATION.md.
#
#   multicast_l2_range: EOS asks for 16383 of the 16384-entry L2MC table for L2
#   multicast alone. On plain Trident2 (trident2.c:13598) L2 multicast and IPMC
#   SHARE that table and each defaults to half. On its own this property is
#   enough to make bcm_attach return -6 BCM_E_FULL, and adding
#   multicast_l3_range=0 beside it -- which is what EOS actually does -- does
#   not rescue it. Taking the SDK default (8192/8192) works.
#   multicast_l3_range: EOS sets it to 0, which under this SDK leaves IPMC with
#   ZERO entries and fails the same way -- also bisected alone. So BOTH range
#   properties are dropped and the SDK's own 8192/8192 split is taken. EOS's
#   16383/0 pair is only valid under EOS's older SDK semantics.
DROP = ("multicast_l2_range", "multicast_l3_range")


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    unit = 0
    minimal = "--minimal" in sys.argv[1:]
    for a in sys.argv[1:]:
        if a.startswith("--unit"):
            unit = int(a.split("=", 1)[1]) if "=" in a else 0
    if len(args) != 2:
        sys.exit(__doc__)
    src, dst = args

    out, seen, skipped = [], set(), 0
    for raw in open(src, encoding="utf-8", errors="replace"):
        line = raw.rstrip("\n")
        if any(line.strip().startswith(p) for p in SKIP_PREFIXES):
            continue
        m = LINE.match(line)
        if not m:
            if line.strip():
                skipped += 1
            continue
        key, val = m.group(1), m.group(2)
        # Rewrite only a trailing unit qualifier.
        base, _, tail = key.rpartition(".")
        if base and tail.isdigit():
            key = "%s.%d" % (base, unit)
        if key.split(".")[0] in DROP:
            continue
        if key in seen:
            continue
        seen.add(key)
        out.append("%s=%s" % (key, val))

    if minimal:
        keep = ("portmap_", "os", "pbmp_xport_xe", "higig2_hdr_mode")
        out = [o for o in out
               if any(o.split("=")[0].split(".")[0] == k
                      or o.startswith(k) for k in keep)]

    out.sort()
    with open(dst, "w") as f:
        f.write("# Generated by tools/mkconfigbcm.py from %s\n" % src)
        f.write("# Live SDK properties captured from EOS, remapped to unit %d.\n"
                % unit)
        f.write("# Do not hand-edit; regenerate instead.\n")
        f.write("\n")
        f.write("# --- required by the user-space BDE, NOT present in EOS's set ---\n")
        f.write("# EOS drives the chip through the kernel BDE with real MSI, so it\n")
        f.write("# never needs this. Our shim deliberately returns -1 from\n")
        f.write("# interrupt_connect rather than pretending to succeed, and without\n")
        f.write("# polled_irq_mode the SDK treats that as fatal:\n")
        f.write("#   soc_attach: could not connect interrupt line -> rv=-1\n")
        f.write("# No unit suffix, so it applies to every unit.\n")
        f.write("polled_irq_mode=1\n")
        f.write("\n")
        f.write("# The TSC SerDes firmware MUST be loaded over MDIO, not the\n")
        f.write("# UCMEM fast path. load_firmware is a PACKED property\n")
        f.write("# (tscmod.c:667-670): low byte = load_mthd, high byte = uc_cksum.\n")
        f.write("# The default load_mthd=2 routes the image through\n")
        f.write("# _soc_trident2_tsc_firmware_set -> XLPORT_WC_UCMEM_DATA, which\n")
        f.write("# silently does nothing through our user-space BDE -- and tscmod\n")
        f.write("# DISCARDS the helper's return value (tscmod.c:331, overwritten by\n")
        f.write("# the next tier1_selector call), so the failure is invisible. The\n")
        f.write("# uC then never runs and every port dies on\n")
        f.write("#   'uC download: timeout: wait for checksum ... crc 0 vs a081'.\n")
        f.write("# 0x101 = load_mthd 1 (word-by-word MDIO, which we have proven\n")
        f.write("# works: 0 MIIM timeouts) + uc_cksum 1 (still verify the CRC).\n")
        f.write("load_firmware=0x101\n")
        f.write("\n")
        for line in out:
            f.write(line + "\n")

    print("wrote %s: %d properties (%d non-matching lines ignored)"
          % (dst, len(out), skipped))
    ports = [o for o in out if o.startswith("portmap_")]
    print("  portmap entries: %d" % len(ports))
    for p in ports[:4]:
        print("    %s" % p)


if __name__ == "__main__":
    main()
