hostname edgenos-7150-ospf
password zebra
log syslog
!
interface et1
!
interface lo
!
router ospf
 ospf router-id 10.101.255.26
 passive-interface lo
 network 10.101.101.24/29 area 0.0.0.0
 network 10.101.255.26/32 area 0.0.0.0
