hostname edgenos-7150-ospf
password zebra
log syslog
!
interface et1
 ip ospf hello-interval 10
 ip ospf dead-interval 40
!
router ospf
 ospf router-id 10.101.101.26
 network 10.101.101.24/29 area 0.0.0.0
